### ISSUE TITLE
Will UIKit for Mac be a supported target for TunnelKit?

### ISSUE THREAD

**Issue by jeroenleenarts** [passepartoutvpn/tunnelkit#108]
# Summary
I'm trying to compile EduVPN with TunnelKit targeted for the Mac. But I am seeing several OpenSSL related issues in `TLSBox.m`. 

### Steps to reproduce

Pick a project with TunnelKit (iOS) enable Mac target on Xcode 11 (tried Beta 2).

### What is the current bug behavior?

Errors:

-  `../Pods/OpenSSL-Apple/frameworks/iPhone/openssl.framework/Headers/opensslconf.h:22:3: Unable to determine target or target not included in OpenSSL build`
`.../Pods/OpenSSL-Apple/frameworks/iPhone/openssl.framework/Headers/bn.h:195:43: Unknown type name 'BN_ULONG'`

### What is the expected correct behavior?

TunnelKit sweetness allowing convenient codebase re-use from an iOS project on Mac.

### Possible fixes suggested remediation

Probably something about target settings / support. Maybe even CocoaPods related?

**Comment by keeshux** [comment]
Fix the `platform` parameter in the Podfile. It's clear that you're referencing iOS pods in a macOS (?) target.

**Comment by jeroenleenarts** [comment]
I'm compiling against UIKit for Mac (Catalyst). Not sure how Cocoapods should be configured yet.

**Comment by jeroenleenarts** [comment]
Might be an as of yet unsupported situation for Cocoapods.

https://github.com/CocoaPods/CocoaPods/issues/8892

**Comment by keeshux** [comment]
Ah, yeah looks "too new".

**Comment by keeshux** [comment]
@jeroenleenarts have you tried upgrading to TunnelKit 2.1.0?

**Comment by jeroenleenarts** [comment]
Yes. But haven’t tried a Mac build as of yet. 2.1.0 has been picked up in the EduVPN codebase. 👍

**Comment by keeshux** [comment]
Nice, but I need feedback on Mac otherwise I'm going to have to close the issue.

**Comment by jeroenleenarts** [comment]
Currently we switched to having Mac as a separate target on EduVPN. So the wish for `uikitformac` support has been reduced.
