### ISSUE TITLE
How to using datacount in tunnelkit

### ISSUE THREAD

**Issue by JackyBaby615** [passepartoutvpn/tunnelkit#109]
After vpn connection is successed, I have to show data count ingoing from and outgoing to vpn server.
I don't understand how to use the function "refreshDataCount()" on  OpenVpnTunnelProvider class.
In that class dataCountInterval member variable is set o by default and i cannot override this variable my networkextension class derived from PacketTunnelProvider.
Are there any sample code related to my problem?
I would be grateful if you could send me the answer.

**Comment by keeshux** [comment]
You access data count via `OpenVPNTunnelProvider.Configuration` from the app:

https://github.com/passepartoutvpn/tunnelkit/blob/a861c69f36abc77e66fe0887b96884261338113e/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider%2BConfiguration.swift#L291
