### ISSUE TITLE
Running Demo Issues

### ISSUE THREAD

**Issue by BioZrod** [passepartoutvpn/tunnelkit#110]
# Summary
Hello I am new to swift and IOS development, I am trying to run the Demo file but I keep getting some errors like this one:

![image](https://user-images.githubusercontent.com/12672464/60204913-c5f57600-9804-11e9-8c83-1c6e014b33f8.png)

After reading some documentations I managed to solve the disambiguate by doing this:

![image](https://user-images.githubusercontent.com/12672464/60204960-eae9e900-9804-11e9-8981-4c2b86803190.png)

I am not sure if that is an Ok fix, also I am unable to find the bytePointer attribute on documentation for the last one.

**Comment by keeshux** [comment]
Xcode and Swift version?

**Comment by BioZrod** [comment]
Xcode 10.2.1 and Swift 5

**Comment by keeshux** [comment]
No issues here. Have you followed the README properly with CocoaPods and all?

**Comment by BioZrod** [comment]
Thank you for your quick response. I cloned the project from GitHub again. This is my current Setup:

MacOS: 10.14 (Mojave)
Xcode Version: 10.1
CocoaPods: 1.7.2
Git version: 2.17.2 (Apple Git-113)
Jazzy: Not Installed
BitCode: Disabled
![image](https://user-images.githubusercontent.com/12672464/60291039-ec7fe380-98ce-11e9-842a-2629e1df7bc0.png)

and I get the following error:

![image](https://user-images.githubusercontent.com/12672464/60291052-f6094b80-98ce-11e9-8d3f-c62eaae2a242.png)

So I Change SWIFT_VERSION to 4.2 for all conflicts:

![image](https://user-images.githubusercontent.com/12672464/60291065-fc97c300-98ce-11e9-9991-8d685402938f.png)

And then I get the errors I described before:
![image](https://user-images.githubusercontent.com/12672464/60291078-03bed100-98cf-11e9-99e7-fe42e4ac11cb.png)

I hope this description might help you give me some insight on what I am doing wrong.

Thank you again for your help.

**Comment by keeshux** [comment]
Make sure to do `bundle install` and then `bundle exec pod install` for any CocoaPods operation and *do not touch* the Pods project. You should never need to do so.

Also, I haven't tested with CocoaPods 1.7.x and by my own experience CocoaPods tends to break very often. Most of the time it's not their fault but Xcode's.

**Comment by keeshux** [comment]
BTW I see you're on Xcode 10.1, which is remarked by the fact that Swift 5 is not recognized.

You must update to 10.2. Non issue.
