### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by melisaozturk** [passepartoutvpn/tunnelkit#113]
# Summary
Hi,
I parsed a ovpn file. But my app isn't connecting . I just changed one method to parse a file . I am not getting any error, it is not working properly. I don't know what did i do wrong. Please help.

### Relevant logs and/or screenshots
 I get this following print on my console.

> VPNStatusDidChange
VPNStatusDidChange: 1
saved preferences
VPNStatusDidChange: 1
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 1
VPNStatusDidChange: 1
VPNStatusDidChange: 1

The method that i changed is below.

`    
private func makeProtocol() -> NETunnelProviderProtocol {

        guard let configurationFileURL = Bundle.main.url(forResource: "dataFile", withExtension: "ovpn")
        else {
            print("File not found")
            fatalError()
        }
        do {
            let configurationFileContent =  try OpenVPN.ConfigurationParser.parsed(fromURL: configurationFileURL)
            
            let builder = OpenVPNTunnelProvider.ConfigurationBuilder(sessionConfiguration: configurationFileContent.configuration)
            
            let configuration = builder.build()
            
            return try! configuration.generatedTunnelProtocol(withBundleIdentifier: VPNViewController.tunnelIdentifier, appGroup: VPNViewController.appGroup)
        }
        catch let error as NSError {
            print(error.localizedDescription)
        }
        let tunnelProtocol = NETunnelProviderProtocol()
        tunnelProtocol.serverAddress = "*****"
        return tunnelProtocol
    }
`

**Comment by keeshux** [comment]
You're returning a dummy `NETunnelProviderProtocol` on error, so any connection attempt will fail silently. Are you sure that no error is raised in the try/catch?

Anyway, remove the last 3 lines, they will cause you trouble. Also replace `try!` with `try`.

**Comment by melisaozturk** [comment]
Ok. I did that. Now i have to return a 'NETunnelProviderProtocol' type value. I am returning it inside of do statement. What do i need to return ?

**Comment by keeshux** [comment]
I think that first of all you should read my comment thoroughly.

**Comment by melisaozturk** [comment]
I run demo project and i am getting same log. It is not connecting. Might it be because of some settings that i did wrong ?

>VPNStatusDidChange: 1
saved preferences
VPNStatusDidChange: 1
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 1
VPNStatusDidChange: 1
VPNStatusDidChange: 1

**Comment by melisaozturk** [comment]
I run on simulator and i have this error.

![image](https://user-images.githubusercontent.com/22300249/61399146-32303a80-a8d6-11e9-8039-09d6d95d9181.png)

**Comment by keeshux** [comment]
The simulator doesn't support VPNs, you must test on a real device.

**Comment by melisaozturk** [comment]
Ok. I understand what you mean earlier. I guess you said that i am handling the error wrong way so i can't see the error. I changed the way handling the error. But i guess it is still wrong.  I don't know how to handle it to see the error. What do you suggest ?

` do {
            let configurationFileContent =  try OpenVPN.ConfigurationParser.parsed(fromURL: configurationFileURL)
            let builder = OpenVPNTunnelProvider.ConfigurationBuilder(sessionConfiguration: configurationFileContent.configuration)   
            let configuration = builder.build()
            return try configuration.generatedTunnelProtocol(withBundleIdentifier: VPNViewController.tunnelIdentifier, appGroup: VPNViewController.appGroup)
        }
   catch {
            fatalError("Error")
            }`

**Comment by keeshux** [comment]
If no fatal error is raised then it should be okay to start with.

Open the Console app on macOS and set the search filter to "BasicTunnel". Then connect to the VPN and see if there's relevant output about why the tunnel is stopping (most surely a configuration issue).

**Comment by melisaozturk** [comment]
I checked and i have some problems so i want to ask,  i used just ' pod 'TunnelKit' ' to put the library into my project. I wonder is there any other things that i had to do or just adding it into podfile is enough.
This is one of the errors:

> Value of NETestAppMapping in the Info.plist for com.melisaozturk.VPN is not a dictionary or is empty

**Comment by keeshux** [comment]
READMEs exist for a reason... By the way, I can help as long as it's about the library, but a VPN is not a good place to start Swift programming. I'm gonna have to close this one. Reach out via email and send me your full code.

**Comment by melisaozturk** [comment]
Ok, you are right. I am sorry to bodhering you. The project is attached
except for opn file. Thank you.

 VPN.zip
<https://drive.google.com/file/d/1M2k2YJ9salt9ZkEUNANVZduWgjLHbbK1/view?usp=drive_web>


Davide De Rosa <notifications@github.com>, 18 Tem 2019 Per, 10:30 tarihinde
şunu yazdı:
