### ISSUE TITLE
Can't open a URL in safari after connect to my server

### ISSUE THREAD

**Issue by OnlyThen** [passepartoutvpn/tunnelkit#115]
# Summary
After connected, If I open a URL in safari, the status of VPN will be disconnect. And In Xcode it will log that "VPNStatusDidChange: 1", And the App still in run, It didn't crush, It just disconnect the vpn automatically.

But If I use the same oven file in Passepartout. It can work. Does I missing some settings in this Demo? The credentials is username/password.

**Comment by OnlyThen** [comment]
oven file look like this:
------------------------------
client
verb 4
connect-retry 2 300
resolv-retry 60
dev tun
remote 192.168.11.14 1194
proto udp
comp-lzo
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
......
</ca>

**Comment by keeshux** [comment]
Look for the tunnel log in the Console app, the error will be clear (surely an encryption mismatch).

**Comment by XiejingJin** [comment]
I have faced same issue , so How to check tunnel log ?

**Comment by XiejingJin** [comment]
hI, You wrote that "Look fr the tunnel login the Console app. the error will be clear( surely an encryption mismatch" 
so my question is where i can check tunnel log?
Please help me , i am beginner to try learning about VPN app programming 
Thank you

**Comment by keeshux** [comment]
I wrote it clearly, it's "in the Console". If you don't know what the Console app is, then it's very likely that you shouldn't be using this library. This is not a good start for Swift beginners.

**Comment by XiejingJin** [comment]
Thank you for your answer ,  so you mean command line programming in swift?

**Comment by keeshux** [comment]
@OnlyThen please post any progress/update or I'm going to close this one as non-issue.

**Comment by OnlyThen** [comment]
There are no more info in Console relevant to the auto disconnect. May be I need to check the code in detail.
