### ISSUE TITLE
Look for the tunnel log in the Console app, the error will be clear (surely an encryption mismatch).

### ISSUE THREAD

**Issue by XiejingJin** [passepartoutvpn/tunnelkit#116]
Look for the tunnel log in the Console app, the error will be clear (surely an encryption mismatch).

_Originally posted by @keeshux in https://github.com/passepartoutvpn/tunnelkit/issues/115#issuecomment-514527665_

**Comment by XiejingJin** [comment]
where is tunnel log?and how can i check it ?

**Comment by keeshux** [comment]
Dude you're abusing what GitHub is for. Please follow up via e-mail.
