### ISSUE TITLE
"route [ip] 255.255.255.255 net_gateway" option in ovpn profile is not working

### ISSUE THREAD

**Issue by briankendall** [passepartoutvpn/tunnelkit#129]
passepartout version 1.8.1
iOS 12.3.1
iPhone 7

I'm trying to set up an OpenVPN profile that routes certain IP addresses or hostnames to the local network's gateway rather than through the VPN. Unfortunately this doesn't seem to be working in passepartout.

I've created an ovpn profile with specific `route` options that I've confirmed works as intended on macOS with both Viscosity and Tunnelblick. This profile works in OpenVPN Connect if the route is specified by IP address. (OpenVPN Connect seems to ignore the `allow-pull-fqdn` option which is why I decided to try passepartout.) So as near as I can tell I have my ovpn profile set up correctly.

**Comment by briankendall** [comment]
I empathize with how hard it is to prioritize features in these sorts of projects. I have a few open source utilities I maintain in my free time and scarcely have time to implement many of the things users request.

I don't think I'll be asking for a refund as the app just costs 2 USD. It's more worthwhile to me to both keep the app and not spend the effort getting the refund!

I am tempted to see if I could possibly implement these features myself and make a pull request. Please feel free not to indulge me if it's a tough question to answer, but do you have a guess of how much work it would be to add in `allow-pull-fqdn` or `net_gateway`?

**Comment by keeshux** [comment]
I moved the issue to TunnelKit in the meanwhile, which is the underlying OpenVPN implementation (actually a subset of).

Off the bat, I believe that `net_gateway` takes looking at the routing table for the target network interface of the VPN (Wi-Fi or cellular). There's helpful code in `RoutingTable.*`, something that I rushed for another flag and TBH is messy as hell. Once there, you pick the default gateway of the relevant `RoutingTableEntry`.

As to `allow-pull-fqdn`, I didn't even know what it does:

> --allow-pull-fqdn
              Allow client to pull DNS names from server (rather than being limited to IP address) for --ifconfig, --route, and --route-gateway.

Why are you in need of such a niche feature? I've probably never seen DNS servers pushed as FQDN.

**Comment by briankendall** [comment]
There are websites that won't work properly when used over my VPN service, or that I need to visit from a particular public IP (such as my home network). But they also don't have a static IP addresses, so creating custom routes for them based on their IP address won't work, at least not consistently. So being able to resolve their hostname after opening a connection to the VPN and creating a route based on that is necessary with my use case.

**Comment by keeshux** [comment]
Got it!

**Comment by briankendall** [comment]
@keeshux If I have questions about your codebase as I try to hack these features in, what would be an appropriate channel for that?

**Comment by keeshux** [comment]
If related to this issue, I would say here. GitHub is the right place where to discuss code things.

**Comment by briankendall** [comment]
@keeshux Do you have any advice on how I can ensure changes I make to tunnelkit will be reflected in my builds of Passepartout? I was going crazy for a little while wondering why the changes I was making weren't being reflected in the app's logs.

I changed Passepartout's podfile so that the line that includes tunnelkit is now `pod_path $tunnelkit_name, $tunnelkit_specs, '..'` so that it uses my locally pulled repo. But so far I haven't been able to get any changes I make to tunnelkit to be reflected in builds of the app unless I go into my DerivedData directory and delete Passepartout.app from it (which I'm guessing forces Xcode to *actually* reassemble its contents). Is there a better way?

**Comment by keeshux** [comment]
The only gotcha I can think of is that you _must_ clean the project each time you update TunnelKit code. It's as stupid as it sounds.

**Comment by briankendall** [comment]
Thanks for the tip!

I've been looking at where tunnelkit parses configurations and it looks like it only uses the options provided by the OpenVPN server at connection time and doesn't use anything from the original opvn file. Is that correct?

**Comment by keeshux** [comment]
It's not correct. It reads client's configuration first, then server's. Look at:

https://github.com/passepartoutvpn/tunnelkit/blob/master/TunnelKit/Sources/Protocols/OpenVPN/ConfigurationParser.swift

**Comment by briankendall** [comment]
Yup, I've been poking through that one. I had gotten confused because I incorrectly assumed that the original ovpn file would be parsed at connection time when in fact it's only parsed when it's imported.

The next thing I'm trying to figure out is whether the routes I define in my ovpn file are being processed at connection time. What I'm finding is that when `OpenVPNTunnelProvider.bringNetworkUp()` is called there are no routes in `OpenVPN.Configuration.ipv4.routes`.

I'm trying to figure out why this is the case. The first thing I looked into was that in `ConfigurationParser.parsed()` it won't add any of the routes unless the ovpn file includes the `ifconfig` option, as the routes are added inside the if block:

    if let ifconfig4Arguments = optIfconfig4Arguments {

however my ovpn file doesn't have an ifconfig line as that's provided by the server at connection time. But even if I do add an `ifconfig` option to my ovpn file then there are still no routes in `OpenVPN.Configuration.ipv4.routes ` when `bringNetworkUp()` is called, and I think that's because they get overwritten when the options from the server are parsed.

Am I on point here? I'm wondering if the parsing logic needs to be changed to allow routes defined in the ovpn file to persist, including when the ovpn file doesn't include the `ifconfig` option.

**Comment by keeshux** [comment]
Brian, you cannot alter the structure of persisted data of an app in use by thousands of users, you cause crashes in a blink. With this in mind, feel free to post your PRs, I'll review them when I'll have time to. Now I'm busy through a release and other stuff.

**Comment by briankendall** [comment]
> Brian, you cannot alter the structure of persisted data of an app in use by thousands of users, you cause crashes in a blink.

Well I'm not proposing making any changes that would break backwards compatibility. From what I see in OpenVPNTunnelProvider it looks like it should be possible to add a new keys without causing issues to already stored data.

Am I correct that `OpenVPN.Configuration` itself is not serialized and stored? It looks like it is reconstituted by parsing the stored data obtained via `NETunnelProviderProtocol`. Granted I'm not familiar with every piece of code as the app is quite large, but I assumed this was the case as otherwise it wouldn't be possible to add support for additional OpenVPN options to the app without causing crashes.

In any case I'll be sure to do my best to test and make sure my changes don't cause crashes when reading persisted data from previous versions of the app. Also I'll try not to poke you too often since you're busy.

**Comment by keeshux** [comment]
The `OpenVPN.Configuration` object is serialized as a map into the VPN profile. It only takes a profile reinstall to fix but it still means manual intervention.

Back to the code, new fields must always be optional and #122 is a good example of how to implement a new field. Do not make changes to ipv4/ipv6 fields as it's absolutely not required. My feeling is that if you parse `net_gateway` as a parameter, you need to look up the routing table to find out how to interpret that value. That's it, no changes to the existing structures.

**Comment by briankendall** [comment]
> The OpenVPN.Configuration object is serialized as a map into the VPN profile. It only takes a profile reinstall to fix but it still means manual intervention.

Okay, I can move forward keeping the structure the same.

Yes I can add `net_gateway` without needing to add new fields, but the issue I'm tackling now is that routes defined in the ovpn file are currently ignored due to the reasons mentioned in previous posts. So Implementing `net_gateway` won't do me any good until that's sorted out.

**Comment by keeshux** [comment]
> > The OpenVPN.Configuration object is serialized as a map into the VPN profile. It only takes a profile reinstall to fix but it still means manual intervention.
> 
> Okay, I can move forward keeping the structure the same.
> 
> Yes I can add `net_gateway` without needing to add new fields, but the issue I'm tackling now is that routes defined in the ovpn file are currently ignored due to the reasons mentioned in previous posts. So Implementing `net_gateway` won't do me any good until that's sorted out.

Routing parameters should be parsed client-side too, the code is shared. The only adjustment is to be done here:

https://github.com/passepartoutvpn/tunnelkit/blob/907c8ec00cad2df5580d3d73ef5fb3a73435a08b/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider.swift#L570-L571

because most other settings are read from `cfg.options` (client), then from `options` (server). In the case of `ipv4`/`ipv6`, `cfg` is skipped altogether.

E.g. you might want to test this quick change:

```
if let ipv4 = options.ipv4 {
```

to something like:

```
if let ipv4 = (cfg.options ?? options).ipv4 {
```

Let me know.

**Comment by briankendall** [comment]
Instead of `cfg.options` did you perhaps mean `cfg.sessionConfiguration`? (`cfg` has no member variable named `options`.)

Regardless none of the Configuration instances I'm aware of contain any of the routes I defined in my ovpn file. I think the issue is in `OpenVPNTunnelProvider+Configuration.swift`.

**Comment by briankendall** [comment]
Instead of `cfg.options` did you perhaps mean `cfg.sessionConfiguration`? (`cfg` has no member named `options`.)

Regardless none of the Configuration instances I'm aware of contain any of the routes I defined in my ovpn file. I think the issue is in `OpenVPNTunnelProvider+Configuration.swift`. The functions there for converting to and from `providerConfiguration` don't include `ipv4` and so the routes don't persist between when I import my ovpn file and when `startTunnel` is called. (Unless I'm missing something important!)

**Comment by keeshux** [comment]
> Instead of `cfg.options` did you perhaps mean `cfg.sessionConfiguration`? (`cfg` has no member named `options`.)

Yes, `cfg.sessionConfiguration`.

> 
> Regardless none of the Configuration instances I'm aware of contain any of the routes I defined in my ovpn file. I think the issue is in `OpenVPNTunnelProvider+Configuration.swift`. The functions there for converting to and from `providerConfiguration` don't include `ipv4` and so the routes don't persist between when I import my ovpn file and when `startTunnel` is called. (Unless I'm missing something important!)

You're right. Are they parsed from the .ovpn though? They should, and you can unit test them before touching `AppExtension`.

**Comment by briankendall** [comment]
I've created a PR #133 with my current work. I'm skeptical about the changes I made in my third commit `"Include ipv4 routes if ifconfig is not specified when parsing config"` and I'm keen to get your thoughts on it.

The issue that it's trying to address is that routes specified in the client's profile should still be added even when that profile doesn't include the `ifconfig` option, but the way things were coded before made it so that any route would be ignored without `ifconfig`. Since changing the structure of `OpenVPN.Configuration` is a non-starter I opted to have all the members of `IPv4Settings` and `IPv6Settings` other than `routes` be assigned the empty string in this circumstance, and then have `OpenVPNTunnelProvider.bringNetworkUp()` check to see if either the server or local options contains IP settings that aren't empty. This strikes me as a rather hacky solution but so far I haven't thought up a better way to handle this.

**Comment by briankendall** [comment]
No worries if you're busy, but have you had a chance to check out the PR?

I have an experimental build I'm running that also adds support for `allow-pull-fqdn`. I'm thinking I could make a separate PR for that if and when you approve of my current one.

**Comment by keeshux** [comment]
Brian, TBH I don't know if I'll consider a PR on these ones. It's for you only (nobody ever asked it so far) and it might break functionality for thousands of happy customers without a 101% focused code review. For now I suggest you keep these changes in your fork, I'm sure you'll understand.

I'll retain the existing conversation for reference but I pretty much will add `net_gateway` to unsupported features in the README and close this issue.

**Comment by briankendall** [comment]
Yes I understand, makes sense. One of the wonderful things about open source is that I can maintain my fork and keep the feature I need. 😉
