### ISSUE TITLE
Implement receiving exit-notify from server ("RESTART" control message)

### ISSUE THREAD

**Issue by fkooman** [passepartoutvpn/tunnelkit#131]
#29 implements sending exit-notify to the server from the client. However, the server also can send this to the client, e.g. when the OpenVPN process is stopped, or the client is disconnected (using `kill` in OpenVPN management interface).

**Comment by keeshux** [comment]
Note: requires refactoring `Authenticator` in order to keep parsing control data outside the authentication scope. The magic string that the server sends as exit notification is "RESTART".
