### ISSUE TITLE
New Cipher And Hash

### ISSUE THREAD

**Issue by OnlyThen** [passepartoutvpn/tunnelkit#134]
I want to use other cipher in SSL. 

I tried to read this part in your code. But I did not add new cipher successfully. So can you write a doc about adding new cipher and hash algorithm. So We can do some contribution.  And do more modifiy.

**Comment by keeshux** [comment]
It's not trivial. You need to look at `CryptoBox` and the `DataPathCrypto` protocols in `Protocols/OpenVPN`. Based on the algorithm, `CryptoBox` may defer the implementation to `[DataPath]CryptoAEAD` or `CBC` or `CTR`.

By the way, what cipher/hash do you need?

**Comment by OnlyThen** [comment]
Thank you! I know this project is using openssl as a framework. And I want to add Chinese SM4 cipher And SM3 hash algorithm. SM4 is like AES 128 and SM3 is like SHA256. they are implemented in [GmSSL](https://github.com/guanzhi/GmSSL). And I have build it to a framework.

**Comment by keeshux** [comment]
Okay, but those won't make it into `master`, so this will be closed.
