### ISSUE TITLE
While connecting app show it need developer update

### ISSUE THREAD

**Issue by lait831** [passepartoutvpn/tunnelkit#136]
# Summary

**Comment by keeshux** [comment]
Description unclear!

**Comment by lait831** [comment]
I am getting this error while connecting to openvpn 
https://firebasestorage.googleapis.com/v0/b/dummy-166d1.appspot.com/o/Screen%20Shot%202019-11-21%20at%2011.06.47%20PM.png?alt=media&token=f2e8a498-e443-4557-a20a-8295e0ab1049

**Comment by keeshux** [comment]
I have absolutely no idea, but I'm 100% sure that it doesn't come from the library, so I'm keeping this closed.

**Comment by lait831** [comment]
my connection status is loosing when i hit connect

https://firebasestorage.googleapis.com/v0/b/dummy-166d1.appspot.com/o/Screenshot%202019-12-03%20at%2012.01.04%20AM.png?alt=media&token=033bfc66-6e6b-45b8-aaee-78714ad97455
