### ISSUE TITLE
Add support for "setenv" option

### ISSUE THREAD

**Issue by OnlyThen** [passepartoutvpn/tunnelkit#139]
# Summary
I want to use setenv option in .ovpn file. But it can't be parsed by tunnelkit. I'am trying add support for setenv. But App will run unsuccessful.
### Steps to reproduce
So does it hard to add support for setenv? What should I do in the code?

**Comment by keeshux** [comment]
Thing is, the concept of script is meaningless in TunnelKit, therefore so is the `setenv` flag.

What do you exactly need to do?

**Comment by OnlyThen** [comment]
I want to using setenv to send some message to the server, such the UUID of this device.

**Comment by keeshux** [comment]
I see! I'll have to have a look at the OpenVPN documentation first. Give me a few days and I'll get back to you.

**Comment by keeshux** [comment]
Do this quick test before anything.

After this line:

https://github.com/passepartoutvpn/tunnelkit/blob/aabdf8382b35618813706a113afe5c09b0f895da/TunnelKit/Sources/Protocols/OpenVPN/Authenticator.swift#L130

add something like:

```
opts.append("setenv UUID 123456")
```

and see if it does what you expect.

**Comment by OnlyThen** [comment]
OK, I will try it. Thanks!

**Comment by keeshux** [comment]
@OnlyThen updates on this? I would close it otherwise.
