### ISSUE TITLE
Saved VPN configuration requires an update

### ISSUE THREAD

**Issue by rakeshdev16** [passepartoutvpn/tunnelkit#142]
I've following the steps detailed in the description and right when I save the VPN configuration in the system Settings the VPN profile is highlighted in red saying that [requires an update](https://imgur.com/a/ViLVMiU). I've seen in several places that the information stored in providerConfiguration property read from the .ovpn file is stored as String and in other cases as Data directly raw from the file, which one is the correct one?

If I install your app and simply pass .ovpn configuration file then it starts working. 

Just wanted to clarify if you are providing the complete code or just partial code in the repo.

**Comment by rakeshdev16** [comment]
My OpenVPN version is 2.4.7

**Comment by keeshux** [comment]
The `providerConfiguration` property is a generic dictionary (key -> value). I have no idea what the "update required" message is about, but other users have had it.

The code is 100% complete. Passepartout uses TunnelKit from CocoaPods (via GitHub).

**Comment by rakeshdev16** [comment]
I presume these files are missing in the code. 
![WhatsApp Image 2019-12-14 at 10 29 09 PM](https://user-images.githubusercontent.com/58626815/70851917-780f2000-1ec1-11ea-94cb-446721d78143.jpeg)

**Comment by rakeshdev16** [comment]
I am not able to run the code.

**Comment by rakeshdev16** [comment]
Do I need https://github.com/passepartoutvpn/passepartout-core-apple as well to run the code.

**Comment by keeshux** [comment]
What are READMEs for?
