### ISSUE TITLE
IPv4 broken on macOS 10.14

### ISSUE THREAD

**Issue by jeroenleenarts** [passepartoutvpn/tunnelkit#146]
# Summary
Somehow IPv4 traffic isn't working through the VPN on MacOS 10.14 (10.15 seems fine)

### Steps to reproduce
Use TunnelKit in an app on MacOS.

### What is the current bug behavior?
Connectivity with IPv4 fails on MacOS 10.14

### What is the expected correct behavior?
It should work.

### Relevant logs and/or screenshots
Please see: https://github.com/eduvpn/ios/issues/191
Especially the pcap logging.

### Possible fixes suggested remediation
This is our current workaround: https://github.com/johankool/tunnelkit/commit/b72222f1e12fc6d217a33fc3aa8c2889525dfec8
( This workaround was included on our repo with this pull req:
https://github.com/eduvpn/ios/pull/193 )

**Comment by efef** [comment]
Possibly the issue in the NETunnelInterface (TunnelKit library) and implementation of writePacket(_:, completionHandler:) and writePackets(_:, completionHandler:). Those methods seems to send the message with same protocol, setted in one place. Apple implementation, NEPacketTunnelFlow at the other side, implies that packets could be sent with different protocols.

**Comment by keeshux** [comment]
Somewhat introduced by `ec2950171b64136a07aea18870854879001ad15d`

**Comment by jeroenleenarts** [comment]
@keeshux We might have a very simple fix for the IPv4/v6 issue on certain MacOS version.

@roop Has created a change on TunnelKit which we are now testing with EduVPN.

More details here: https://github.com/roop/tunnelkit/commit/753927f36b354d986859d9a75bca1944a35e8ea0

If it works out @roop has promised to issue a pull request. :)
