### ISSUE TITLE
"Update Required" (iOS)

### ISSUE THREAD

**Issue by Octolus** [passepartoutvpn/tunnelkit#149]
When importing the .ovpn configuration, it throws a red error saying "Update Required".

Has anyone else experienced this? The only topic I found about it was: https://forums.openvpn.net/viewtopic.php?t=27123

We've tried that, and it still does not work.

Screenshot: https://i.imgur.com/ShIJP0C.png

Been stuck on this problem for almost three months without any solutions to fix it, also been in contact with tunnelkit dev which told me to make a topic here. Hopefully, someone had the same issue and found a fix :)

_Would literally pay for a solution in BTC._

**Comment by pahnev** [comment]
Happened to me in situation where my ca, clientCertificate or clientKey was wrong. Also all these can be valid on their own, but they obviously need to match each other and what your server expects.

**Comment by Octolus** [comment]
> Happened to me in situation where my ca, clientCertificate or clientKey was wrong. Also all these can be valid on their own, but they obviously need to match each other and what your server expects.

I am able to upload the .ovpn config file, if anyone could see if they get the same problem. We're using those .ovpn files already, and clients are using other apps on both iOS/Mac to connect fine.

**Comment by NasrullahKhan** [comment]
ProjectEditor > Your App Network Extension > Build Settings > Deployment > Change iOS Deployment Target (to your project deployment target iOS 11 12 etc)

**Comment by amir-ardalanuk** [comment]
@NasrullahKhan  thanks you! the problem was about the deployment target that was set on 13.1 but my device version is 12.2

**Comment by keeshux** [comment]
@Octolus please try the suggested fix and close the issue if needed.

**Comment by keeshux** [comment]
@NasrullahKhan thank you very much for your hint, honestly I've never faced the issue so I couldn't have a chance to fix it either. I appreciate that your comment helped out a few people over here.

**Comment by Octolus** [comment]
@NasrullahKhan For some reason, the developers of my app (who are running into this issue) claim it's still not working. Do you have any email, Skype, Telegram or anything we could chat on? I'll pay you for your time.

**Comment by NasrullahKhan** [comment]
> @NasrullahKhan thank you very much for your hint, honestly I've never faced the issue so I couldn't have a chance to fix it either. I appreciate that your comment helped out a few people over here.

glad to hear that. The secret of happiness is helping others. (y)

**Comment by NasrullahKhan** [comment]
> @NasrullahKhan For some reason, the developers of my app (who are running into this issue) claim it's still not working. Do you have any email, Skype, Telegram or anything we could chat on? I'll pay you for your time.

we can discuss on skype nasrullah_win8@hotmail.co.uk.

**Comment by kandrelczyk** [comment]
Hi @Octolus ,
I'm getting this exact same issue in my app. Did you manage to solve it?

**Comment by kandrelczyk** [comment]
Manged to fix it. For anyone looking for some clues the solution was to create a new target in XCode (File->New->Target) using 'Network Extension' template. 
This new target needs to compile the "OpenVPNPacketTunnelProvider.swift' file (Build Phases->Compile Sources)
This new target needs to get 'TunnekKitOpenVPNAppExtension' as a dependency (Build Phases->Link Binary with libraries).
The main target needs to get the Network Extension target as a dependency (Build Phases->Dependencies).
The main target also gets 'TunnelKitOpenVPN' as a dependency in 'Link Binary with Libraries'. 
Both targets get 'NetworkExtension.framework' as a 'Link Binary with Libraries' dependency. 


After doing all this and the 'Update required' error went away.

**Comment by nhatminhx6** [comment]
Hi @Octolus , did you fix this issue ? i have the same issue, tried many but still cant solve, please help

**Comment by AnitaGVMTechnologies** [comment]
I am facing same issues , i have applied solutions but not getting resolved the issue
