### ISSUE TITLE
Connection Detail - disconnect without any log

### ISSUE THREAD

**Issue by amir-ardalanuk** [passepartoutvpn/tunnelkit#150]
# I am  trying to my server but the connection only switch between connection(2) and disconnected(1) 

### Log:
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 1
VPNStatusDidChange: 1
VPNStatusDidChange: 1
![Screen Shot 2020-01-25 at 3 34 07 PM](https://user-images.githubusercontent.com/12419118/73120848-3b3a4c80-3f88-11ea-9fee-032b5897f0f0.png)
![Screen Shot 2020-01-25 at 3 31 46 PM](https://user-images.githubusercontent.com/12419118/73120849-3bd2e300-3f88-11ea-826f-033d750dfcd2.png)

is there an option to set on the verbose log for connection?

**Comment by keeshux** [comment]
Read the jazzy documentation, and start with the demo.
