### ISSUE TITLE
Device not Configured

### ISSUE THREAD

**Issue by amir-ardalanuk** [passepartoutvpn/tunnelkit#151]
# Summary
I am trying to connect to the server and set all session builder requirement
### Steps to reproduce
I used the tunnel sample code just replace our server config

### What is the current bug behavior?
it could not connect to the server and when I checked the console find out this issue's 
![Screen Shot 2020-01-28 at 2 14 44 PM](https://user-images.githubusercontent.com/12419118/73257750-8eefa480-41d9-11ea-8875-e71c39688f47.png)
'Failed: Device not configured' 
and Log : 
VPNStatusDidChange: 1
VPNStatusDidChange: 1
connection satatus 1
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 5
VPNStatusDidChange: 5
VPNStatusDidChange: 5
VPNStatusDidChange: 1
VPNStatusDidChange: 1
VPNStatusDidChange: 1

### What is the expected correct behavior?
connect to the server

**Comment by keeshux** [comment]
Answer is right in the log: "Socket timed out waiting for activity, cancelling...".

Now it's the second or third rushed issue/comment you post in a week. Take the necessary time to understand what you're doing in the first place, before posting issues on GitHub. I'm a bit annoyed at this point.

Closing this, again.
