### ISSUE TITLE
macOS app crash when we export the build after notarization.

### ISSUE THREAD

**Issue by NasrullahKhan** [passepartoutvpn/tunnelkit#152]
# Summary
i developed the macOS app with tunnelkit sucessfully, during the development everything is working fine but when i export the mac app after notarization. the app crash without opening

NOTE: i tried to export both my macOS app and tunnelkit macOS sample app both are crashing after exporting with Developer ID (.i.e. distribute to customer directly without mac app store)

### Steps to reproduce
1. Notarize macOS application with Developer ID
2. Try to open the app ( by click on xyz.app file)

### What is the current bug behavior?
```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
System Integrity Protection: enabled

Crashed Thread:        0
```

### What is the expected correct behavior?
App should run after notarization successfully completes.

### Relevant logs and/or screenshots
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010fdcc000-000000010fed1000 [ 1044K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x0000000116501000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffedfe33c08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000116501000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

```

### Possible fixes suggested remediation
i tried many ways.
1. The app work fine after export when i remove network extension cabapilities
2. I tried to create the manual provisioning profiles of Distribute/Developer ID Applicatio for both the macOS application and application network extension.
3. I tried the macOS app store distribution method to export the .pkg file.
4. I tried the macOS Development method
5. I tried to directly export the archive app (this worked by only on my macbook)

**Comment by keeshux** [comment]
@NasrullahKhan you can't use Developer ID because NetworkExtension requires App Store deployment. I suspect that is the issue.

**Comment by NasrullahKhan** [comment]
But here it says Developer ID supports network extension
https://help.apple.com/developer-account/#/devadf555df9

Also there are application like expressvpn and nordvpn and many others with openvpn outside the mac app store so they must be using network extension.  how they are doing it?

**Comment by keeshux** [comment]
Okay, let me be more exact: Packet Tunnel Providers can’t be deployed with Developer ID.

Look here:

https://developer.apple.com/documentation/networkextension/packet_tunnel_provider

and here:

https://forums.developer.apple.com/thread/125508

Those apps you mention must be using either embedded instances of the OpenVPN executable as a separate process, or raw sockets with low-level interface manipulation.

**Comment by NasrullahKhan** [comment]
do you have idea about TunnelBlick. i think they are not using network extension (packet tunnel).

https://github.com/Tunnelblick/Tunnelblick

**Comment by keeshux** [comment]
Not  exactly the context to talk about Tunnelblick. I’m going to close this one.

**Comment by NasrullahKhan** [comment]
Btw Thanks for your responses.

**Comment by keeshux** [comment]
I can tell you that Tunnelblick is one of those cases where they simply bundle a thin UI wrapped around the original OpenVPN client. Anyway, you'd better ask in their repos.

**Comment by NasrullahKhan** [comment]
i developed iOS app with tunnelkit. and i will upload next week the app with tunnelkit openvpn protocols. will apple approve it directly or i will have to do something or license etc.?

**Comment by keeshux** [comment]
Please contact me on info@passepartoutvpn.app

**Comment by 2856571872** [comment]
> i developed iOS app with tunnelkit. and i will upload next week the app with tunnelkit openvpn protocols. will apple approve it directly or i will have to do something or license etc.?

Hello, I also encountered this problem in mac, how to solve it in the end?
