### ISSUE TITLE
Force connection via IPv4

### ISSUE THREAD

**Issue by alexkoester** [passepartoutvpn/tunnelkit#153]
Hi. 

Is it possible to force a connection via IPV4?  Unfortunately the parameter of OVPN (proto TCP4) does not seem to work.  An attempt is always made to continue to establish the connection via IPV6.  

The parameter works with OVPN without problems.

Log:
15:07:20 - DNS resolve hostname: XXXXX.myfritz.net
15:07:20 - DNS resolved addresses: ["xxxx:xxxx:xxxx:xx:xxxx:xxxx:xxx:xxxx", "xx.xx.xx.xx]
15:07:20 - Will connect to xxxx:xxxx:xxxx:xx:xxxx:xxxx:xxx:xxxx

Thanks.

**Comment by keeshux** [comment]
@alexkoester please contact me on beta@passepartoutvpn.app to test this in beta. Thanks!

**Comment by keeshux** [comment]
@alexkoester I'd like to know if I can close this issue.

**Comment by alexkoester** [comment]
Hello, sorry a little stressful at the moment.  I will test the whole tonight every autumn and then I will let you know.  I'm currently reinstalling OpenVPN on the NUC, so I can't test it anymore.

MfG A. Köster
> Am 09.04.2020 um 12:20 schrieb Davide De Rosa <notifications@github.com>:
> 
> I'd like to know if I can close this issue.

**Comment by alexkoester** [comment]
Works perfectly, will test it more intensively over the holidays.  Good job!  Yours sincerely

**Comment by keeshux** [comment]
Awesome! Thanks for your time, keep me updated.

**Comment by alexkoester** [comment]
Hello, after a long test I noticed that despite the switch "Proto tcp4" an attempt is first made to establish a connection via IPv6.  After that, a connection is established via IPv4.  This takes longer to establish a connection.  

I also noticed in the debug log that "Current SSID" always says None.

**Comment by keeshux** [comment]
@alexkoester please let me know about 2293

**Comment by alexkoester** [comment]
@keeshux Unfortunately the same problem.  First IPv6 then IPv4.  Have checked all parameters again, "proto tcp4" is definitely entered.  The app was also completely deleted and reinstalled.

> 13:05:24 - Starting tunnel...
13:05:24 - App version: Passepartout 1.11.0 (2293)
13:05:24 - 	Protocols: [TCP:443]
13:05:24 - 	Cipher: AES-256-CBC
13:05:24 - 	Digest: HMAC-SHA1
13:05:24 - 	Compression framing: comp-lzo
13:05:24 - 	Compression algorithm: lzo
13:05:24 - 	Client verification: enabled
13:05:24 - 	TLS wrapping: disabled
13:05:24 - 	TLS security level: 0
13:05:24 - 	Keep-alive interval: never
13:05:24 - 	Keep-alive timeout: never
13:05:24 - 	Renegotiation: never
13:05:24 - 	Server EKU verification: disabled
13:05:24 - 	Gateway: not configured
13:05:24 - 	DNS: not configured
13:05:24 - 	MTU: 1250
13:05:24 - 	Debug: true
13:05:24 - 	Masks private data: true
13:05:24 - Current SSID: none (disconnected from WiFi)
13:05:24 - Creating link session
13:05:24 - No endpoints available, will resort to DNS resolution
13:05:24 - DNS resolve hostname: <masked>
13:05:24 - Unrolled endpoints: [<masked>:TCP:443, <masked>:TCP:443]
13:05:24 - DNS resolved addresses: ["<IP6>", "<IP4>"]
13:05:24 - Pick resolved endpoint: <masked>:TCP:443
13:05:24 - Will connect to <masked>:443
13:05:24 - Socket type is NETCPSocket
13:05:24 - Socket state is connecting (endpoint: <masked> -> in progress)
13:05:24 - Socket state is waiting (endpoint: <masked> -> in progress)
13:05:29 - Socket timed out waiting for activity, cancelling...
13:05:29 - Reasserting flag set
13:05:29 - Try next endpoint: <masked>:TCP:443
13:05:29 - Socket state is cancelled (endpoint: <masked> -> in progress)
13:05:29 - Cleaning up...
13:05:29 - Tunnel did stop on request
13:05:29 - Disconnection is recoverable, tunnel will reconnect in 1000 milliseconds...
13:05:30 - Tunnel is about to reconnect...
13:05:30 - Creating link session
13:05:30 - Pick current endpoint: <masked>:TCP:443
13:05:30 - Will connect to <masked>:443
13:05:30 - Socket type is NETCPSocket
13:05:30 - Socket state is connecting (endpoint: <masked> -> in progress)
13:05:30 - Socket state is connected (endpoint: <masked> -> <masked>)
13:05:30 - Starting VPN session

**Comment by alexkoester** [comment]
And now in my WLAN no Connection and the WLAN Connection break. 

13:16:09 - Starting tunnel...
13:16:09 - App version: Passepartout 1.11.0 (2293)
13:16:09 - 	Protocols: [TCP:443]
13:16:09 - 	Cipher: AES-256-CBC
13:16:09 - 	Digest: HMAC-SHA1
13:16:09 - 	Compression framing: comp-lzo
13:16:09 - 	Compression algorithm: lzo
13:16:09 - 	Client verification: enabled
13:16:09 - 	TLS wrapping: disabled
13:16:09 - 	TLS security level: 0
13:16:09 - 	Keep-alive interval: never
13:16:09 - 	Keep-alive timeout: never
13:16:09 - 	Renegotiation: never
13:16:09 - 	Server EKU verification: disabled
13:16:09 - 	Gateway: not configured
13:16:09 - 	DNS: not configured
13:16:09 - 	MTU: 1250
13:16:09 - 	Debug: true
13:16:09 - 	Masks private data: true
13:16:09 - Current SSID: none (disconnected from WiFi)
13:16:09 - Creating link session
13:16:09 - No endpoints available, will resort to DNS resolution
13:16:09 - DNS resolve hostname: <masked>
13:16:09 - Unrolled endpoints: [<masked>:TCP:443, <masked>:TCP:443]
13:16:09 - DNS resolved addresses: ["IPV6", "IPV4"]
13:16:09 - Pick resolved endpoint: <masked>:TCP:443
13:16:09 - Will connect to <masked>:443
13:16:09 - Socket type is NETCPSocket
13:16:09 - Socket state is connecting (endpoint: <masked> -> in progress)
13:16:09 - Socket state is connected (endpoint: <masked> -> <masked>)
13:16:09 - Starting VPN session
13:16:09 - Send hard reset
13:16:09 - Negotiation key index is 0
13:16:09 - Control: Enqueued 1 packet [0]
13:16:09 - Control: Write control packet {HARD_RESET_CLIENT_V2 | 0, sid: 86ac4fa464681037, pid: 0, [0 bytes]}
13:16:09 - Send control packet (14 bytes): 3886ac4fa4646810370000000000
13:16:09 - Failed LINK read: Error Domain=kNWErrorDomainPOSIX Code=54 "Connection reset by peer" UserInfo={NSDescription=Connection reset by peer}
13:16:09 - Socket state is disconnected (endpoint: <masked> -> <masked>)
13:16:09 - Cleaning up...
13:16:09 - Tunnel did stop (error: linkError)
13:16:09 - Flushing log...

--- EOF ---

13:16:09 - Starting tunnel...
13:16:09 - App version: Passepartout 1.11.0 (2293)
13:16:09 - 	Protocols: [TCP:443]
13:16:09 - 	Cipher: AES-256-CBC
13:16:09 - 	Digest: HMAC-SHA1
13:16:09 - 	Compression framing: comp-lzo
13:16:09 - 	Compression algorithm: lzo
13:16:09 - 	Client verification: enabled
13:16:09 - 	TLS wrapping: disabled
13:16:09 - 	TLS security level: 0
13:16:09 - 	Keep-alive interval: never
13:16:09 - 	Keep-alive timeout: never
13:16:09 - 	Renegotiation: never
13:16:09 - 	Server EKU verification: disabled
13:16:09 - 	Gateway: not configured
13:16:09 - 	DNS: not configured
13:16:09 - 	MTU: 1250
13:16:09 - 	Debug: true
13:16:09 - 	Masks private data: true
13:16:09 - Current SSID: none (disconnected from WiFi)
13:16:09 - Creating link session
13:16:09 - No endpoints available, will resort to DNS resolution
13:16:09 - DNS resolve hostname: <masked>
13:16:09 - Unrolled endpoints: [<masked>:TCP:443, <masked>:TCP:443]
13:16:09 - DNS resolved addresses: ["IPV6", "IPV4"]
13:16:09 - Pick resolved endpoint: <masked>:TCP:443
13:16:09 - Will connect to <masked>:443
13:16:09 - Socket type is NETCPSocket
13:16:09 - Socket state is connecting (endpoint: <masked> -> in progress)
13:16:09 - Socket state is connected (endpoint: <masked> -> <masked>)
13:16:09 - Starting VPN session
13:16:09 - Send hard reset
13:16:09 - Negotiation key index is 0
13:16:09 - Control: Enqueued 1 packet [0]
13:16:09 - Control: Write control packet {HARD_RESET_CLIENT_V2 | 0, sid: 96b64b474ca5e600, pid: 0, [0 bytes]}
13:16:09 - Send control packet (14 bytes): 3896b64b474ca5e6000000000000
13:16:09 - Failed LINK read: Error Domain=kNWErrorDomainPOSIX Code=54 "Connection reset by peer" UserInfo={NSDescription=Connection reset by peer}
13:16:09 - Socket state is disconnected (endpoint: <masked> -> <masked>)
13:16:09 - Cleaning up...
13:16:09 - Tunnel did stop (error: linkError)
13:16:09 - Flushing log...

**Comment by keeshux** [comment]
I actually see a problem here:

```
13:16:09 - Starting tunnel...
13:16:09 - App version: Passepartout 1.11.0 (2293)
13:16:09 - 	Protocols: [TCP:443]   <--- should be "TCP4" here
13:16:09 - 	Cipher: AES-256-CBC
13:16:09 - 	Digest: HMAC-SHA1
```

Try "Remove VPN configuration", reinstall the profile and post a new debug log.

**Comment by alexkoester** [comment]
I have already noticed this.  That's why the app is uninstalled, profile violated, other ports used and so on.  Only TCP: XXX appears.  My OVPN-File see above.
