### ISSUE TITLE
VPN Compression Directive Error

### ISSUE THREAD

**Issue by jsonpaul** [passepartoutvpn/tunnelkit#155]
# Summary

Hello everyone,

My .ovpn file include "compress lzo". When I try to parse with **ConfigurationParser** it shows  **unsupportedConfiguration(option: "compress lzo")** .

### Steps to reproduce

Set compress lzo to ovpn file and try to connect vpn. 
Without compress lzo I can establish connection but server side shows error. 

### What is the current bug behavior?

I can't connect to vpn when I add "compress lzo" option to my ovpn file.When I delete , it connect to vpn but server shows "Bad LZO decompression header error".

### What is the expected correct behavior?

Connect VPN even using "compress lzo" option

### Relevant logs and/or screenshots

Log:
`Error info: unsupportedConfiguration(option: "compress lzo")`

Ovpn file:
```
client
dev tun
proto tcp-client
sndbuf 0
rcvbuf 0
remote xx.xx.xx.xx xxxx
resolv-retry infinite
nobind
persist-key
persist-tun
auth-user-pass
remote-cert-tls server
auth SHA512
auth-nocache
compress lzo
cipher AES-256-CBC
key-direction 1
verb 3
<ca>
...
</ca>
<tls-auth>
....
</tls-auth>
``` 

Example of my code : 
```swift
    private func makeProtocol() -> NETunnelProviderProtocol {
        do {
            let credentials = OpenVPN.Credentials(textUsername.text!, textPassword.text!)
            let configurationFileURL = URL(fileURLWithPath: self.documentDirectory()+"/test.ovpn")
            let file = try OpenVPN.ConfigurationParser.parsed(fromURL: configurationFileURL)
            var builder = OpenVPNTunnelProvider.ConfigurationBuilder(sessionConfiguration: file.configuration)
            builder.shouldDebug = true
            builder.masksPrivateData = false
            let configuration = builder.build()
            return try! configuration.generatedTunnelProtocol(
                withBundleIdentifier: ViewController.tunnelIdentifier,
                appGroup: ViewController.appGroup,
                credentials: credentials
            )
        } catch {
            print("Error info: \(error)")
            print("Failed to send a message to the provider")
            return NETunnelProviderProtocol()
        }
    }
}
```

**Comment by keeshux** [comment]
LZO is not included in the TunnelKit pod by default. You must include the `Extra/LZO` pod in your `Podfile`. E.g.:

```
pod 'TunnelKit'
pod 'TunnelKit/Extra/LZO'
```

**Comment by jsonpaul** [comment]
Thanks a lot. That worked like a charm!
