### ISSUE TITLE
No internet access after vpn connected

### ISSUE THREAD

**Issue by manveersinghdodiya** [passepartoutvpn/tunnelkit#157]
When vpn connection establish successfully not able to connect access internet for some times like 2-3 minutes. After 2-3 minutes i can able to access any web page or application. Also when my iphone is connected with wifi and tries to connect with vpn wifi icons hide and it switches to mobile then vpn connection establish then after 2-3 minutes again wifi icon enables on screen.

**Comment by keeshux** [comment]
@manveersinghdodiya I told you to attach a "Debug log" from the app. Either you read what I say or I'll close the issue.
