### ISSUE TITLE
Use Secure Enclave

### ISSUE THREAD

**Issue by aevtyushin** [passepartoutvpn/tunnelkit#160]
Hi,

Is it possible to use tunnelkit with a private key from Secure Enclove?

The procedure is as follows:

- Generate a key in Secure Enclave;
- Create a .csr file with it;
- Based on .csr files, a certificate is issued to me;
- When connecting to a VPN, I specify the certificate and somehow use the Secure Enclave (where is the private key).

Is it possible? If so, is there any example of how to use this?

As I understand it, the NEVPNProtocol class already has an identityReference property where you can pass the certificate link and private key from Keychain.

But I don’t understand if it can be used for OpenVPNSession? If so, how?

**Comment by keeshux** [comment]
The `identityReference` field is used in bundled IPsec/IKEv2 implementations of `NEVPNProtocol`. As is, TunnelKit only takes PKI input (certs and keys) in PEM format via `NETunnelProviderProtocol.providerConfiguration` and ignores any `identity*` field.

I never used "Secure Enclave", but if you can get a PEM out of it, you're good to go.
