### ISSUE TITLE
OpenSSL-Apple not installing after running "pod install"

### ISSUE THREAD

**Issue by bemomilib** [passepartoutvpn/tunnelkit#164]
# Summary
When adding pod 'TunnelKit' to my pod file and then running pod install the process enters an infinite sleep/grep loop
### Steps to reproduce
pod install
### What is the current bug behavior?
enters an infinite sleep/grep loop or throws xcrun: error: SDK "iphoneos" cannot be located
### What is the expected correct behavior?
should install tunnelkit
### Relevant logs and/or screenshots
<img width="641" alt="Screen Shot 2020-04-16 at 04 11 10" src="https://user-images.githubusercontent.com/53345906/79399328-4f468680-7f98-11ea-947a-e286d547482b.png">

<img width="1568" alt="Screen Shot 2020-04-16 at 04 08 23" src="https://user-images.githubusercontent.com/53345906/79399184-eced8600-7f97-11ea-8cf4-add9e9500e28.png">

### Possible fixes suggested remediation
On issue #66 a solution was mentioned, which I tried and it did not work. The possible solution might be similar.

**Comment by keeshux** [comment]
Read error messages before even creating an issue.
