### ISSUE TITLE
Support `fragment` option

### ISSUE THREAD

**Issue by fumoboy007** [passepartoutvpn/tunnelkit#174]
# Summary

ExpressVPN is a popular VPN provider. It seems to require the `fragment` option. `TunnelKit` should support the option.

**Comment by keeshux** [comment]
Nope, it shouldn't. It's a useless feature that ExpressVPN is lazy about for God knows what reason. I've contacted them multiple times to no avail, and in 4 years I've seen nobody else using it.

If you however contribute the patch to support `fragment`, I'm definitely happy to review it for integration.

**Comment by fumoboy007** [comment]
I see. I’ll ask them about it too. However, I’m not an expert; can you provide me with some rationale for why `fragment` shouldn’t be used and what they can do to fix it?

**Comment by keeshux** [comment]
From `man openvpn`, quite extreme scenarios:

> It should also be noted that this option is not meant to replace UDP fragmentation at the IP stack level.  It is only meant as a last resort when path  MTU discovery is broken.  Using this option is less efficient than fixing path MTU discovery for your IP link and using native IP fragmentation instead.
>
> Having said that, there are circumstances where using OpenVPN's internal fragmentation capability may be your only option, such as tunneling a UDP multicast stream which requires fragmentation.

They may drop it, but trust me they will not.
