### ISSUE TITLE
How to utilise BasicTunnelExtension-iOS correctly?

### ISSUE THREAD

**Issue by houmie** [passepartoutvpn/tunnelkit#180]
Hello,

I got the Demo working and it works brilliantly.

Now that I'm trying to port it over to my own app, I'm struggling with couple of classes. I don't understand how the Extension is supposed to work and I read the Readme many times and looked at the code for couple of hours. I can't figure it out.

For example:
```
private let vpn = StandardVPNProvider(bundleIdentifier: tunnelIdentifier)
let neCfg = NetworkExtensionVPNConfiguration(title: "Prototype", protocolConfiguration: proto, onDemandRules: [])
```
Both these classes can't be found, despite ```import TunnelKit```

I think this has to do something with that extension. May you please provide some more details? Thank you

**Comment by keeshux** [comment]
Please stop creating _issues_ for what are in fact _questions_.

**Comment by houmie** [comment]
Apologies. I suppose Github doesn't allow any other form of communication other than through issues. Sorry to bother you.
