### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by gmcha321** [passepartoutvpn/tunnelkit#181]
Hi, first of all thanks for this fantastic library.

The question I have is if I were to write my own ios app (and push it to the app store), what are the rules with regards to linking with this code base? I see that some parts are dual licensed and most of the rest is GPLv3. Pretty sure many have asked this and many will ask in the future. Perhaps some clarity would help.

**Comment by keeshux** [comment]
What parts except dependencies? _Everything_ is GPLv3.

As long as you publish your own source code fully, you owe nothing except giving credit in your software documentation.
