### ISSUE TITLE
Adapt to ios14

### ISSUE THREAD

**Issue by chrisyu-chn** [passepartoutvpn/tunnelkit#183]
Adapt to ios14

In NetworkExtension.framework, the function named `open func readMinimumLength(_ minimum: Int, maximumLength maximum: Int, completionHandler completion: @escaping (Data?, Error?) -> Void)` at iOS13,  translate `open func readMinimumLength(_ minimum: Int, maximumLength maximum: Int, completionHandler completion: @escaping (Data, Error?) -> Void)` at iOS14.

`(Data?, Error?) -> Void`  ==>  `(Data, Error?) -> Void`

Need modify file `TunnelKit/Sources/Protocols/OpenVPN/AppExtension/NETCPLink.swift`  line 67

**Comment by jurajhilje** [comment]
@chrisyu-chn
Just FYI, had the same issue when building TunnelKit with the Xcode 12 Beta 1, but not in the latest Xcode 12 Beta 6.
I think that suggested change in code could break build in Xcode 11.

**Comment by keeshux** [comment]
@jurajhilje thanks for the info. It sounds like a mistype from Apple, non-optional doesn't make sense there. In fact:

https://developer.apple.com/documentation/networkextension/nwtcpconnection/1406156-readminimumlength

```swift
func readMinimumLength(_ minimum: Int, 
         maximumLength maximum: Int, 
     completionHandler completion: @escaping (Data?, Error?) -> Void)
```

I'm gonna close this for now.

**Comment by chrisyu-chn** [comment]
@jurajhilje @keeshux  thinks.
