### ISSUE TITLE
support DOMAIN-SEARCH push option

### ISSUE THREAD

**Issue by fkooman** [passepartoutvpn/tunnelkit#184]
# Summary

OpenVPN 2.5 will support DOMAIN-SEARCH to specify search domains, next to the DOMAIN option for specifying the domain the client will be located in.

> Support setting DHCP search domain
    A new option --dhcp-option DOMAIN-SEARCH my.example.com has been defined, and Windows support for it is implemented (tun/tap only, no wintun support yet). Other platforms need to support this via --up script (Linux) or GUI (OSX/Tunnelblick).

From the OpenVPN 2.5 manpage:

```
DOMAIN name
    Set Connection-specific DNS Suffix to name.

DOMAIN-SEARCH name
    Add name to the domain search list.  Repeat this option to add more entries. Up to 10 domains are supported.
```

It seems the current implementation allows for multiple DOMAIN options to be specified and uses those as search domains instead of setting the "connection-specific DNS suffix", but I am not 100% sure...

From what I understand there should be only 1 `DOMAIN` "push option", and there can be >1 `DOMAIN-SEARCH` options.

**Comment by fkooman** [comment]
Currently the code takes the first "DOMAIN" and sets that as the connection specific domain, and sets all of them as the search domains.

https://github.com/passepartoutvpn/tunnelkit/blob/65234cefa3dfb4c3f1559d69e549502ac2be4430/TunnelKit/Sources/Protocols/OpenVPN/AppExtension/OpenVPNTunnelProvider.swift#L698

I guess the easiest (to maintain backwards compatibility, if that's a thing with DOMAIN/DOMAIN-SEARCH, would be to simply merge whatever comes from DOMAIN and DOMAIN-SEARCH. It will remain correct to set the first "DOMAIN" as the connection specific domain. 

What I don't yet know is whether the DOMAIN option itself also needs (again) to be part of the search domains or if this is something the OS does automatically. On Windows it does not, but it probably won't hurt...

**Comment by fkooman** [comment]
Note that on Windows, if the server sends multiple `DOMAIN` options, the *last* one is used as connection specific domain and not the first one. The others are ignored.

**Comment by roop** [comment]
I’d like to work on this issue but I’m not entirely sure what the desired implementation should be. @keeshux: Can you please help me figure that out?

This is what I understand:

  - In OpenVPN:
      - Both DOMAIN and DOMAIN-SEARCH are dhcp-options, which are network parameters that can be pushed from the server
      - OpenVPN 2.5 documentation says:
           - DOMAIN _name_: Set Connection-specific DNS Suffix to _name_
           - DOMAIN-SEARCH _name_: Add _name_ to the domain search list. Repeat this option to add more entries. Up to 10 domains are supported.
      - DOMAIN is supported in OpenVPN 2.0 onwards. DOMAIN-SEARCH is supported in OpenVPN 2.5 onwards.
  - In TunnelKit at present:
      - “DOMAIN _name_” is added as a DNS search domain. It can be pushed multiple times to specify multiple DNS search domain entries. The first <name> is used to set NEDNSSettings.domainName.
      - “DOMAIN-SEARCH _name_” is not parsed or supported.

There are the questions I have:

  - It seems to me that both DOMAIN and DOMAIN-SEARCH exist for the same purpose. The only difference is that one supports one entry only and the other supports multiple entries. Is that a correct assessment?
  - Do we want to support multiple “DOMAIN _name_” commands? (I think the OpenVPN documentation suggests that there can be only one, but would it be a breaking change for TunnelKit if we disallow multiple entries now?)

**Comment by keeshux** [comment]
@roop check out the PR, I think it's the easiest way to address your concerns altogether.

**Comment by roop** [comment]
@keeshux Thanks, this looks great.

To summarize the PR:

- Multiple "DOMAIN-SEARCH _name_" commands are recognized
- Only the first "DOMAIN _name_" command is recognised. Subsequent "DOMAIN _name_" commands are ignored.
- A "DOMAIN _name_" entry becomes the first search domain (and set as NEDNSSettings.domainName) even if it comes after some "DOMAIN-SEARCH _name_" commands

**Comment by keeshux** [comment]
> @keeshux Thanks, this looks great.
> 
> To summarize the PR:
> 
> * Multiple "DOMAIN-SEARCH _name_" commands are recognized
> * Only the first "DOMAIN _name_" command is recognised. Subsequent "DOMAIN _name_" commands are ignored.
> * A "DOMAIN _name_" entry becomes the first search domain (and set as NEDNSSettings.domainName) even if it comes after some "DOMAIN-SEARCH _name_" commands

Yup that’s the intention. If you confirm the implementation I’ll go ahead and merge it.

**Comment by roop** [comment]
@keeshux Yes, this is good.

This deviates a bit from the Windows OpenVPN client implementation (that @fkooman mentioned above -- the Windows client picks the last DOMAIN, this implementation picks the first), but that's a negligible concern.

Please go ahead and merge this.

**Comment by keeshux** [comment]
> Note that on Windows, if the server sends multiple `DOMAIN` options, the _last_ one is used as connection specific domain and not the first one. The others are ignored.

What about other platforms in that case?

**Comment by fkooman** [comment]
> > Note that on Windows, if the server sends multiple `DOMAIN` options, the _last_ one is used as connection specific domain and not the first one. The others are ignored.
> 
> What about other platforms in that case?

```
        // push "dhcp-option DOMAIN example.com"
        // push "dhcp-option DOMAIN example.org"
        // push "dhcp-option DOMAIN example.com"
        // push "dhcp-option DOMAIN-SEARCH example.org"
```

This is the way to make it work everywhere (at the moment). Note that `example.com` is both the first and the last so it works on TunnelKit and on Windows. The `DOMAIN-SEARCH` currently already works fine on Windows and in Viscosity (macOS/Windows). I didn't test Android as I have no idea how to test this as I don't currently have a server with proper split DNS and split tunneling to test with.

As for Linux/NetworkManager-OpenVPN: https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/issues/56

**Comment by keeshux** [comment]
No, exclude TunnelKit as is today from the equation. What’s OpenVPN behavior on non-Windows when multiple DOMAIN option are pushed? Which one is picked?

**Comment by fkooman** [comment]
> No, exclude TunnelKit as is today from the equation. What’s OpenVPN behavior on non-Windows when multiple `DOMAIN` options are pushed? Which one is picked?

I didn't investigate fully... DNS handling is always platform dependent and it also depends on the implementation. Tunnelblick for example behaves differently from Viscosity, and both use OpenVPN. So one would have to analyze all implementations. 

The OpenVPN project (OpenVPN Community) only handles DNS (and DOMAIN/DOMAIN-SEARCH) on Windows and leave the rest up to the specific platform integrations/implementations.  There are also some implementations that use SEARCH-DOMAIN instead of DOMAIN-SEARCH. Some support multiple DOMAIN options and use the additional ones as search domains instead of connection specific domain name. I also don't know what the official OpenVPN Connect applications do on the various platforms...

In the end I think projects should follow what is done by OpenVPN Community for Windows to keep it consistent as that is the only "official" open source OS integration provided by the project.

**Comment by fkooman** [comment]
I *do* think that the current PR is good enough for now though :)

**Comment by roop** [comment]
The PR has now been modified (commit 6b8d88f) to make the behaviour as follows:

  - Multiple "DOMAIN-SEARCH name" commands are recognized
  - Only the _last_ "DOMAIN name" command is recognised. Any earlier "DOMAIN name" commands are ignored.
  - A "DOMAIN name" entry becomes the first search domain (and set as NEDNSSettings.domainName) even if it comes after some "DOMAIN-SEARCH name" commands

This makes TunnelKit match the behaviour of the the OpenVPN Windows client w.r.t. handling of DOMAIN and DOMAIN-SEARCH. This is perfect.
