### ISSUE TITLE
error load @rpath/openssl.framework/openssl

### ISSUE THREAD

**Issue by sergeymild** [passepartoutvpn/tunnelkit#188]
add to Podfile
pod 'TunnelKit'

made pod install
and open .xcodeproj

after run app i see that error.

if i run Demo project i see the same error.

dyld: Library not loaded: @rpath/openssl.framework/openssl
Referenced from: /private/var/containers/Bundle/Application/5D051150-0F1C-429E-A757-9DE27966AC2F/my.app/my
Reason: image not found

dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by jaroslavas** [comment]
How you managed to fix this?

**Comment by ajrahim** [comment]
@sergeymild Have you been able to resolve this issue?

**Comment by ajrahim** [comment]
@jaroslavas If you're still running into this issue I had to manually include the xcode project and remove all the podfile references in the targets (for the Tunnelkit xcode project). Once I did that I added the following to my podfile:

  pod 'SwiftyBeaver'
  pod 'OpenSSL-Apple', '~> 1.1.1h.10'

**Comment by jaroslavas** [comment]
Yup, this is what I did. Thanks for sharing for everybody!
