### ISSUE TITLE
Handle "push-peer-info" option

### ISSUE THREAD

**Issue by alexandresoro** [passepartoutvpn/tunnelkit#202]
# Summary

Hello,
I am opening this issue to check and confirm if the OpenVPN option"push-peer-info" is implemented in tunnelkit.
By looking at the documentation, I do not see mention of it, so I assume that this is not handled today.
If I am mistaken, feel free to close this issue.

The reason why I am opening this issue is that I am trying to connect to my workplace VPN for which the configuration has recently been upgraded to handle custom 2FA authentication.
This authentication now relies on some client information, possibly the hardware MAC address to detect if we are trying to connect from a new device.

I am able to connect properly - or at least trigger the 2FA mechanism - from the official OpenVPN client on Windows, or via Tunnelblick that uses the official stack from macOS, but I am unable to achieve the same results with Passepartout from macOS or iOS.
The authentication step is getting rejected with a "bad credentials" message.

If I remove this "push-peer-info" option from the ovpn config file, I am unable to connect with any OpenVPN client, which suggests that some info sent by the client with this flag is indeed necessary for my workplace server.

As per the documentation:

_"When --push-peer-info is enabled the additional information consists of the following data:
IV_HWADDR=<mac address> -- the MAC address of clients default gateway
IV_SSL=<version string> -- the ssl version used by the client, e.g. "OpenSSL 1.0.2f 28 Jan 2016".
IV_PLAT_VER=x.y - the version of the operating system, e.g. 6.1 for Windows 7.
UV_<name>=<value> -- client environment variables whose names start with "UV_""_

My guess is that in my case, the IV_HWADDR tag is used by my company to detect if the machine that tries to connect is a new one or not, so by not sending it, I am rejected.

Thanks a lot for your work, and your app. I'd be glad to ditch the official stack - which I feel bloated - if I could manage to connect again to my workplace's VPN!

### What is the current bug behavior?

I am unable to connect to my company's VPN with Passepartout, but I am able to do so with the official OpenVPN stack and the exact same configuration.
Investigations show that it is possibly linked to the "push-peer-info" option

### What is the expected correct behavior?

I would be able to connect to my company's VPN

### Relevant logs and/or screenshots

None relevant logs

**Comment by keeshux** [comment]
I think that a debug log of a successful connection from e.g. Tunnelblick would shed some light on what it's sending to the server. Send it to issues@passepartoutvpn.app with a reference to this issue.

I can try to fix this on macOS, still I wonder if OpenVPN Connect on iOS is really working. I ask because MAC address on iOS is not something you can read easily, if it's possible at all.

**Comment by alexandresoro** [comment]
Hello @keeshux ,

I sent the email with the relevant logs. I am unable to reproduce the issue right now, but I at least I provided you the logs from openVPN connect on iOS in case you wish to have a look at how they deal with the options from push-peer-info

Regards

**Comment by keeshux** [comment]
IV_HWADDR can't be sent, but this proved not be an issue following private conversation.
