### ISSUE TITLE
Is it legal to upload to appstore ?

### ISSUE THREAD

**Issue by b3hroo2** [passepartoutvpn/tunnelkit#205]
Hello everyone

We are vpn provider and launched our android app 2 years ago (openvpn protocol) now we want to develop and publish our ios app.
I read that openvpn library licensed under _GPLV3_ and appstore don't allow to publish it.

So my question is that how **passepartoutvpn** published on appstore ?
Does it have agreement with openvpn ?

Could we develop base on **passepartoutvpn** core ?

**Comment by keeshux** [comment]
Hi, you may upload the app if you disclose its source code fully under the GPL. Otherwise, you would need to purchase a proprietary license.
