### ISSUE TITLE
Adjust the timing/mechanism of reconnection on network roaming

### ISSUE THREAD

**Issue by plkgq** [passepartoutvpn/tunnelkit#207]
When the mobile network and wifi switch, the reconnection may fail, can I adjust the timing and mechanism of reconnection

**Comment by plkgq** [comment]
Thank you very much for your treatment, I am using the library, except for the reconnection problem, it is very easy to use. I will follow this library for a long time. In addition, I hope to enable the one-time reward function. If possible, I would like to invite the author to have a cup of coffee：）

**Comment by keeshux** [comment]
Currently, the reconnection mechanism is automated and cannot be fine-tuned. It's not something I plan to change unless I will refactor the OpenVPN tunnel (which is very dangerous).
