### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by plkgq** [passepartoutvpn/tunnelkit#212]
When I connected for a while, an error message appeared, I did not set the usesPIAPatches property

![image](https://user-images.githubusercontent.com/11607068/126296354-63da6b96-8046-4701-a85a-32052ea8ea08.png)

**Comment by plkgq** [comment]
use tcp connection

**Comment by keeshux** [comment]
What's exactly the issue you mean to bring up?

**Comment by plkgq** [comment]
A Connection reset by peer error occurred during reconnection. Why does this happen?

**Comment by plkgq** [comment]
Connected for about 50 minutes, disconnected, and the above error occurred

**Comment by keeshux** [comment]
Closed for inactivity.

**Comment by keeshux** [comment]
Being a one-off report, I tend to believe this was an occasional issue. Closing.
