### ISSUE TITLE
xcode 13 pod install fail

### ISSUE THREAD

**Issue by plkgq** [passepartoutvpn/tunnelkit#216]
When I created a new project using xcode 13, I just executed pod install and the installation failed
![image](https://user-images.githubusercontent.com/11607068/134765607-8e71b7d5-f0c4-4452-a69f-91bc9c1b74e5.png)

**Comment by plkgq** [comment]
cocoapod version is 1.11.2

**Comment by keeshux** [comment]
Please share your `Podfile`.

**Comment by plkgq** [comment]
> 请分享您的`Podfile`.

![image](https://user-images.githubusercontent.com/11607068/135013353-55e6f6f6-9aa9-45ef-801e-a44bbc94419d.png)

**Comment by plkgq** [comment]
platform :ios, '12.0'
use_frameworks!

target 'SwiftVPN' do
  pod 'WKWebViewJavascriptBridge'
  pod 'SwiftyJSON'
  pod 'DeviceKit'
  pod 'KakaJSON'
  pod 'CocoaLumberjack/Swift'
  pod 'Toast-Swift'
  pod 'FFRouter'
  pod 'JKSwiftExtension'
  pod 'DynamicColor'
  pod 'GTMBase64'
  pod 'Cartography'
  pod 'MJRefresh'
  pod 'LSTPopView'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'YYCache'
  pod 'WHC_KeyboardManager'
  pod 'CocoaDebug', :configurations => ['Debug']
  pod 'CryptoSwift', '~> 1.4.0'
  pod 'SwiftyRSA'
  pod 'YYText'
  pod 'Eureka'
  pod 'SwiftEntryKit'
  pod 'lottie-ios'
  pod 'LGSideMenuController'
  pod 'SkyFloatingLabelTextField'
  pod 'JXSegmentedView'
  pod 'AppsFlyerFramework'
  # Network
  pod 'Alamofire'
  pod 'Moya'
  # Image
  pod 'Kingfisher'
  # Layout
  pod 'SnapKit'
  # Data
  pod 'KeychainAccess'
  pod 'SVProgressHUD'
  pod 'TunnelKit'
end




this is another project podfile

**Comment by keeshux** [comment]
Just tested on Xcode 13 with the same Podfile without any issue.

```
platform :ios, '12.0'

target 'TestTunnelKit (iOS)' do
    use_frameworks!
    pod 'TunnelKit'
end
```

**Comment by plkgq** [comment]
> 刚刚在 Xcode 13 上使用相同的 Podfile 进行了测试，没有任何问题。CocoaPods 也是 1.11.2
> 
> ```
> platform :ios, '12.0'
> 
> target 'TestTunnelKit (iOS)' do
>     use_frameworks!
>     pod 'TunnelKit'
> end
> ```

**Comment by plkgq** [comment]
> Just tested on Xcode 13 with the same Podfile without any issue. CocoaPods also 1.11.2
> 
> ```
> platform :ios, '12.0'
> 
> target 'TestTunnelKit (iOS)' do
>     use_frameworks!
>     pod 'TunnelKit'
> end
> ```

I think I solved it, it should be pod cache problem,   pod cache clean --all, it succeeded
