### ISSUE TITLE
VPNStatusDidChange: connecting VPNStatusDidChange: disconnected

### ISSUE THREAD

**Issue by faisyleo** [passepartoutvpn/tunnelkit#217]
# Summary

### Steps to reproduce
Connect with my Bundle Identifier and Extensions and then run the application OPenVPN is not connected

### What is the current bug behavior?
There is no bug behavior

### What is the expected correct behavior?
Connect with my OVPN file

### Relevant logs and/or screenshots
VPNStatusDidChange: disconnected
VPNStatusDidChange: connecting
VPNStatusDidChange: disconnected

Attached

<img width="867" alt="Screenshot 2021-10-05 at 2 33 33 PM" src="https://user-images.githubusercontent.com/41253902/135998256-6594a7b8-8178-4b23-b410-612b72ab53d4.png">

### Possible fixes suggested remediation
Add a demo video for connectivity

**Comment by keeshux** [comment]
Follow the demo for comparison, you are misconfiguring something.

**Comment by faisyleo** [comment]
> Follow the demo for comparison, you are misconfiguring something.

I complete follow the steps here is the update on My project kindly check I attached the screenshot.

**Comment by wfs498121294** [comment]
+1  i donwload the demo   and  have the same problem
