### ISSUE TITLE
Add net_gateway / net_gateway_ipv6 gateway flag for --route and --route-ipv6

### ISSUE THREAD

**Issue by fkooman** [passepartoutvpn/tunnelkit#225]
Add support to push routes to VPN clients to route *that* specific range over the client's default gateway instead of the VPN. This allows e.g. for tunneling all traffic over the VPN *except* certain destinations, or excluding traffic to a (sub)range from a pushed range over the VPN.

See openvpn(8) `--route` documentation and also https://community.openvpn.net/openvpn/ticket/1161.

**Comment by roop** [comment]
@keeshux: Are you open to having this feature added if I make a PR?

**Comment by keeshux** [comment]
> @keeshux: Are you open to having this feature added if I make a PR?

Of course!
