### ISSUE TITLE
Same subnet: VPN and WiFi

### ISSUE THREAD

**Issue by flobernd** [passepartoutvpn/tunnelkit#238]
Hi there,

Im trying to get OpenVPN working on my mobile phone (Passepartout) at work.

Wifi there has - let's say - 192.168.2.0/24 subnet assigned.

My OpenVPN server pushes 192.168.0.0/16 to the client which works just fine. I can access all the subnets **except** 192.168.2.0/16. It seems like traffic is simply not routed through the tunnel but hits the default gateway instead.

Is this a known restriction on iOS or do you have any tips for me?

Edit: 
Ahh was supposed to create this issue in the proper repository, but somehow messed up ^^ sorry for that.

Best,
Florian

**Comment by keeshux** [comment]
In fact this is the proper repository!

**Comment by keeshux** [comment]
Before anything, does this work with OpenVPN Connect?

**Comment by flobernd** [comment]
@keeshux 
I actually planned to test this before opening an issue, but we were sent to home office due to the current COVID19 situation and I'm not able to do so in the next months :-/ I might be able to reproduce by connecting to the VPN server while in my home network. If I send traffic to a machine in the same subnet it should go through the tunnel and not directly hit the gateway if everything works fine. Not sure if you have some kind of test setup at home anyways, otherwise I will happily try to reproduce it on my side using both, `Passepartout` and `OpenVPN Connect`.

**Comment by keeshux** [comment]
Yes please. Try to reproduce the setup and provide me with the generic server/client conf for me to test as well.
