### ISSUE TITLE
TunnelKitManager.KeychainError.add error occurs when compiling TunnelKitWireGuard ios demo

### ISSUE THREAD

**Issue by Au1rxx** [passepartoutvpn/tunnelkit#241]
# Summary
I encountered an error when compiling the TunnelKitWireGuard ios demo: TunnelKitManager.KeychainError.add 

Please help me solve the problem, thank you!

### Steps to reproduce
Compile the TunnelKitWireGuard ios demo and it will appear. I confirm that I have configured the correct WireGuard information.

### Relevant logs and/or screenshots
TunnelKitDemo-iOS[36830:12846042] TunnelKitDemo_iOS/WireGuardViewController.swift:104: Fatal error: 'try!' expression unexpectedly raised an error: TunnelKitManager.KeychainError.add

**Comment by keeshux** [comment]
https://github.com/passepartoutvpn/tunnelkit#demo
