### ISSUE TITLE
framework not found SwiftyBeaver

### ISSUE THREAD

**Issue by plkgq** [passepartoutvpn/tunnelkit#242]
hi, after i add this plugin using spm, when i compile, i get the following error
![image](https://user-images.githubusercontent.com/11607068/148769119-15ac3bfb-8ed4-476a-a7a4-fef18c6ba7ef.png)
I don't know which step is wrong, please help

**Comment by plkgq** [comment]
![image](https://user-images.githubusercontent.com/11607068/148770147-0a82008d-63cc-4d48-86ec-c70d503f3402.png)
and the SwiftyBeaver version used is different
I don't know if it has anything to do with it

**Comment by plkgq** [comment]
![image](https://user-images.githubusercontent.com/11607068/148770797-70acac4f-fb6e-47fe-9f51-a344f4f6ba16.png)
This is how I installed

**Comment by keeshux** [comment]
Sorry, I'll check this out next week back from holidays.

**Comment by keeshux** [comment]
No problem on my end. Maybe the issue is about mixing SwiftPM and CocoaPods?
