### ISSUE TITLE
Unable to Integrate Tunnel Kit through SPM

### ISSUE THREAD

**Issue by NomanAziz51** [passepartoutvpn/tunnelkit#243]
# Summary
Tried to add a tunnel kit through SPM in my project but SPM was stuck at Validate tunnel kit. I used the latest code 13.2.1.

### Steps to reproduce
Copy and paste library link from Github and SPM stuck at the initial stage in SPM.

### What is the current bug behavior?
The same response tried a different solution and also tried to reinstall my Xcode.

### What is the expected correct behavior?
Smoothly integrate Tunnel Kit through SPM.

### Relevant logs and/or screenshots
Screen Shot attached.
![WhatsApp Image 2022-01-19 at 11 19 40 PM](https://user-images.githubusercontent.com/54615930/150191778-f2844fbd-551c-4f89-896f-eb8463e07af4.jpeg)

### Possible fixes suggested remediation

**Comment by NomanAziz51** [comment]
When I try to run this library I face following issue.
![WhatsApp Image 2022-01-21 at 3 14 33 PM](https://user-images.githubusercontent.com/54615930/150511517-8df4630e-cd02-40f6-b4c1-63f1fb90d375.jpeg)

Application is working fine for the iOS  but when I tried to run code in macOS I faced an issue regarding weired guard
I tried every available solution on internet but not succeed

**Comment by keeshux** [comment]
Based on your latest post I guess you managed to integrate the package. I referenced the comment in a new (potential) issue.

**Comment by Leo7654** [comment]
Need golang
