### ISSUE TITLE
Can't distribute mac app

### ISSUE THREAD

**Issue by newfuture33** [passepartoutvpn/tunnelkit#247]
I have developed mac app. But I can't distribute, because of Network Extension. 
If remove this option, can't connect to vpn.
Please help me.
![image](https://user-images.githubusercontent.com/34529419/162790294-5231f62e-8495-409d-b000-4486ce218e39.png)

**Comment by keeshux** [comment]
Not an issue with TunnelKit. You cannot use NetworkExtension with Developer ID.

**Comment by newfuture33** [comment]
Then, no method to resolve this problem?

**Comment by keeshux** [comment]
I don't know and btw this is not where to ask.

**Comment by 2856571872** [comment]
> Then, no method to resolve this problem?
Is there any solution? Use the developer ID to distribute
