### ISSUE TITLE
ld: library not found for -lwg-go

### ISSUE THREAD

**Issue by phanvandaILG** [passepartoutvpn/tunnelkit#248]
# Summary
I follow the instructions but still error ld: library not found for -lwg-go\
Help me, thanks you so much
![Screen Shot 2022-04-15 at 11 19 19](https://user-images.githubusercontent.com/96431025/163517987-188d3442-eb21-4c37-bffd-50c3a833805d.png)
![Screen Shot 2022-04-15 at 11 18 47](https://user-images.githubusercontent.com/96431025/163517989-e0f2c620-81f1-4040-879b-73ede7f4084e.png)
![Screen Shot 2022-04-15 at 11 17 41](https://user-images.githubusercontent.com/96431025/163517991-b1c34a62-dcc1-4fd3-99a3-cd1539a1bc9b.png)
![Screen Shot 2022-04-15 at 11 19 27](https://user-images.githubusercontent.com/96431025/163517976-8a4cb839-5b31-43cc-be0f-a8fb1bad3eb5.png)

**Comment by phanvandaILG** [comment]
why close my issues ?

**Comment by keeshux** [comment]
Because it’s not an issue with the library, check your bogus script path.
