### ISSUE TITLE
tls-crypt-v2 support

### ISSUE THREAD

**Issue by tkmw1985** [passepartoutvpn/tunnelkit#252]
Any plans to support tls-crypt-v2 ?

**Comment by keeshux** [comment]
Not really.

**Comment by houmie** [comment]
Sorry, I'm new to this project and just stumbled upon this.  Does this mean if the OpenVPN server is using `tls-crypt-v2` for handshake, this client won't work?  Thanks

**Comment by keeshux** [comment]
> Sorry, I'm new to this project and just stumbled upon this. Does this mean if the OpenVPN server is using `tls-crypt-v2` for handshake, this client won't work? Thanks

Exactly.
