### ISSUE TITLE
DataCount is nil

### ISSUE THREAD

**Issue by phanvanda** [passepartoutvpn/tunnelkit#254]
Hi, after i connect success VPN, i want to check datacount using VPN.
I create function run this to get dataCount every 3 seconds. But dataCount is nil
I follow your demo, i don't find about this problem.
Can you guide me about this? Thansk so much, this is my code:

File connect:
 func connect() {
        do {
            let config = try OpenVPN.ConfigurationParser.parsed(fromContents: content!).configuration
            cfg = OpenVPN.ProviderConfiguration.init("openVPN", appGroup: appGroup, configuration: config)
            
            Task {
                try await vpn.reconnect(
                    tunnelIdentifier,
                    configuration: cfg!,
                    extra: nil,
                    after: .seconds(2)
                )
            }
            
            executeRepeatedly()
        } catch {
            print(error)
        }
    }
    
    private func executeRepeatedly() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) { [weak self] in
            print(self?.cfg?.dataCount ?? "error1")
            self?.executeRepeatedly()
        }
    }

File Provider:
import NetworkExtension
import TunnelKitOpenVPNAppExtension

class PacketTunnelProvider: OpenVPNTunnelProvider {
}

**Comment by keeshux** [comment]
App Group entitlements incorrect/missing.
