### ISSUE TITLE
How to create a working example WireGuard?

### ISSUE THREAD

**Issue by dmitrymaslov99** [passepartoutvpn/tunnelkit#257]
I'm trying to create a minimal working example to use the guard on iOS. I can't find documentation anywhere on how to do this. I looked at the official repository (https://github.com/WireGuard/wireguard-apple), but there is nothing there.
Can someone tell me how to make a minimum working example of a wireguard?

**Comment by f0r3s1** [comment]
First, you need to close Xcode and then go to stroyka and nosit' kirpichi

**Comment by keeshux** [comment]
I wonder if some people will ever understand what “Issues” stand for. Closing.
