### ISSUE TITLE
Issue with bitcode between TunnelKitOpenVPN and openssl

### ISSUE THREAD

**Issue by Jdgmx** [passepartoutvpn/tunnelkit#259]
# Summary

I'm testing TunnelKit for use it in a project but I ran with this issue when compiling for iOS 15.0
I'm aware that I have to set ENABLE_BITCODE to NO in my project. Put when linking I get the following issue:

`Ld /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/PackageFrameworks/TunnelKitOpenVPN_245E25865209A034_PackageProduct.framework/TunnelKitOpenVPN_245E25865209A034_PackageProduct normal (in target 'TunnelKitOpenVPN' from project 'TunnelKit')`
`ld: '/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/PackageFrameworks/openssl.framework/openssl' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/PackageFrameworks/openssl.framework/openssl' for architecture arm64`

What I understand is that TunnelKitOpenVPN has bitcode enable while open-ssl has not.

### Steps to reproduce

Just created a new project using Swift packages and build it.

### What is the current bug behavior?

Build fails.

### What is the expected correct behavior?

Build succeeds.

### Relevant logs and/or screenshots

Relevant information is that I imported the framework into Xcode using Swift packages. The documentation indicates to use Homebrew, but I couldn't find the formulae in Homebrew's website.

### Possible fixes suggested remediation

Maybe provide TunnelKitOpenVPN with bitcode disabled.

**Comment by keeshux** [comment]
You should describe in detail how you are using the library in your project.

**Comment by Jdgmx** [comment]
Hello.
I just added the project Github's URL into the Swift package manager in Xcode. _"Apparently"_ everything downloaded including the dependencies, my project compiles correctly but I get the linking issue mentioned above. I thought that most likely Swift Packages are not supported, so digging around over the Internet I found an example that uses Cocoapods. I copied the Podfile into my project but I ran into [issues](https://github.com/passepartoutvpn/openssl-apple/issues/46) when Cocapods compiles the SSL library.

So I think at this point my question is how is the correct way to integrate TunnelKit into my app. The readme file says that we should use Homebrew, but I couldn't find the formula on Homebrew's website, or an example that uses it.

Now, I'm observing that Passepartout has a local Packages.swift file with all the dependencies. I'll try that,

**Comment by Jdgmx** [comment]
Now I'm getting:

'Source files for target OpenVPNAppExtension should be located under /Users/.../VPNCore/Sources/OpenVPNAppExtensiontarget 'OpenVPNAppExtension' referenced in product 'OpenVPNAppExtension' is empty'

Where VPNCore is my package.

**Comment by keeshux** [comment]
> Hello. I just added the project Github's URL into the Swift package manager in Xcode. _"Apparently"_ everything downloaded including the dependencies, my project compiles correctly but I get the linking issue mentioned above.

^ This is the way to go, do use SwiftPM and refer to the TunnelKit Demo as to how. I'm closing this as it's not an issue with the library.
