### ISSUE TITLE
Can not archive app due to "Command ExternalBuildToolExecution failed with a nonzero exit code" with WireGuardKit target

### ISSUE THREAD

**Issue by shikanoji** [passepartoutvpn/tunnelkit#264]
# Summary
So i successfully built  my app on devices, fixed this issue before by setting Go Path in target's build setting.
But when i try to archive app, this issue happens again, and i am struggle to find out the problem.

My macbook is 15 inch m1 pro,  macOS Monterey 12.4 with Xcode 13.4.1
### Steps to reproduce
Archive app
### Relevant logs and/or screenshots
<img width="1624" alt="Screen Shot 2022-07-03 at 22 54 23" src="https://user-images.githubusercontent.com/6409041/177047418-4728f31e-f1f8-4c8f-bd19-179408a33134.png">

**Comment by pzyno** [comment]
How did you solve this Issue, could you tell me ?

**Comment by keeshux** [comment]
> How did you solve this Issue, could you tell me ?

https://github.com/passepartoutvpn/tunnelkit#manual-xcode-steps
