### ISSUE TITLE
the connecting  immediately disconnected

### ISSUE THREAD

**Issue by whitefox0102** [passepartoutvpn/tunnelkit#266]
hi
I got the issue like #218 #229
I had check my configuration many times
and the tunnel bundle id is correct

I just did a few steps
1. clone the project
2.change the App Groups and Keychain Sharing group
App IDs and Tunnel extension id and use my provisioning profile (demo-iOS,Tunnel-iOS,WireGuardTunnel-iOS)
3.modify the Configuration
4.run the project
5.set the IP address and username password
6.press connect button

and the console log always print

17:19:27 DEBUG NetworkExtensionVPN.notifyReinstall():264 - VPN did reinstall (com.bw.business.ap02-dev.Tunnel): isEnabled=true
VPNStatusDidChange: connecting
17:19:27 DEBUG NetworkExtensionVPN.notifyStatus():278 - VPN status did change (com.bw.business.ap02-dev.Tunnel): isEnabled=true, status=2
VPNStatusDidChange: disconnecting
17:19:28 DEBUG NetworkExtensionVPN.notifyStatus():278 - VPN status did change (com.bw.business.ap02-dev.Tunnel): isEnabled=true, status=5
VPNStatusDidChange: disconnected

please help me thank you~~

**Comment by sendwave** [comment]
Yes, I met same issue, could you please tell me how to solve it?

**Comment by chmcj** [comment]
I met same issue, could you please tell me how to solve it?

**Comment by keeshux** [comment]
Debug the tunnel, not the application. You can both look for the tunnel log in the Console and set breakpoints in the tunnel code. There's not much more I can do to help you.
