### ISSUE TITLE
Is the minimum required iOS 12 or 13?

### ISSUE THREAD

**Issue by houmie** [passepartoutvpn/tunnelkit#268]
Hello,

This looks like a great project! 👍🏼 

Looking at the cocoapods: https://cocoapods.org/pods/TunnelKit it seems that the minimum required iOS version is 12.0.
But on Github it says 13.0.  Which one is correct?  We still have many iPhone 6 users with iOS 12.0. It would be a shame if the minimum was 13.0.

Also on Github page under ```Installation``` it doesn't say anything about installing this via pod. Is the pod outdated perhaps?
What is the correct way of installing this?

Many Thanks

**Comment by keeshux** [comment]
CocoaPods version is unmaintained. The current library only works with SwiftPM, and the minimum target is iOS 13 as stated in the package manifest.
