### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ChineseManCJ** [passepartoutvpn/tunnelkit#270]
Undefined symbols for architecture arm64:
  "_darwin_arm_init_mach_exception_handler", referenced from:
      _x_cgo_init in libwg-go.a(000006.o)
  "_darwin_arm_init_thread_exception_port", referenced from:
      _threadentry in libwg-go.a(000006.o)
      _x_cgo_init in libwg-go.a(000006.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![20220812125704](https://user-images.githubusercontent.com/16795419/184287675-98e20493-d6a0-4811-9965-4715194324ab.jpg)

**Comment by keeshux** [comment]
Go back to the README.
