### ISSUE TITLE
  "VPN status keeps connecting until timeout" using tunnelkit at iPadOS 16 Beta, but it was ok at iOS  16 beta or earlier system like iOS15

### ISSUE THREAD

**Issue by waiwaib** [passepartoutvpn/tunnelkit#271]
everything is ok in iOS16 Beta 7, but when testing at  iPadOS:

The app seems can't be using OpenVPN. I check the log and don't find an error msg, just the VPN status keeps connecting

Because the official version of iPadOS is about to be released, I need to solve this problem urgently.
@keeshux 
thanks~

macOS: 12.5.1
XCode version: Xcode 14 Beta 6
iPadOS version: iPadOS 16.1 Beta 7

**Comment by waiwaib** [comment]
Specifically, I found the root cause is  setTunnelNetworkSettings func stuck until timeout , completion handlers not excute

**Comment by keeshux** [comment]
> Specifically, I found the root cause is NETunnelProvider.setTunnelNetworkSettings func stuck until timeout, completion handlers not execute

Report a bug to Apple instead.

**Comment by waiwaib** [comment]
> Report a bug to Apple instead.

yes, I already report to Apple. wait for apple's response.

**Comment by keeshux** [comment]
> > Report a bug to Apple instead.
> 
> yes, I already report to Apple. wait for apple's response.

Thank you man. They are quite careless but maybe beta regressions are more watched out for. Fingers crossed.

**Comment by keeshux** [comment]
Tested iPadOS 16 beta 7. No issues. Closing this.

**Comment by waiwaib** [comment]
> Tested iPadOS 16 beta 7. No issues. Closing this.

thanks, I just test it, works well! 
seems Xcode 14 Beta debug install version will has this problem, and I just use the  Xcode 14.0， this has been fixed!❤️
