### ISSUE TITLE
Demo always disconnect, console log show: "Tearing down XPC connection due to setup error: Error Domain=NEAgentErrorDomain Code=2"

### ISSUE THREAD

**Issue by sendwave** [passepartoutvpn/tunnelkit#277]
# Summary
When run with tunnelkit demo, App always disconnect, log show:

```
VPNStatusDidChange: connecting
VPNStatusDidChange: disconnected
```
Check in console tool, log show: 
`Tearing down XPC connection due to setup error: Error Domain=NEAgentErrorDomain Code=2`
<img width="1217" alt="图片" src="https://user-images.githubusercontent.com/5556927/191982842-26e28139-8d72-48ad-9837-170f18a63f3e.png">

### Steps to reproduce
Run with demo app, all settings is OK according to README.md.
  
Could anyone please to help me?
Thank you! Thank you! Thank you!

**Comment by sendwave** [comment]
Resolved it!
Re-check all of the id and group-id.

**Comment by maulikm235** [comment]
i am facing same issue in tunnelkit wireguard, anyone have solution?
