### ISSUE TITLE
How to set "ss" protocol in TunnelKit?

### ISSUE THREAD

**Issue by TalentDev0401** [passepartoutvpn/tunnelkit#283]
# Summary
I am developing both iOS and Android VPN app.
Android works well. But, iOS is not working.
In android project, I used "ss" protocol. But, I am not sure how can I configure "ss" protocol in Tunnelkit.
Hope you to solve this small issue in a short time.
Thanks.

**Comment by keeshux** [comment]
Nothing that TunnelKit supports, given it's not even clear what you're talking about.
