### ISSUE TITLE
Support cipher none

### ISSUE THREAD

**Issue by RaviKumarAndroid** [passepartoutvpn/tunnelkit#303]
tunnel kit is not supporting cipher none. its automatically using fallback.  can we add cipher none or maybe some simple patch?? to support cipher none???

**Comment by RaviKumarAndroid** [comment]
When i print configuration it shows using a fallback cipher as 
Remotes: [<masked>:TCP:443]
15:18:31 INFO Configuration.print():660 - 	Cipher: AES-128-CBC
15:18:31 INFO Configuration.print():665 - 	Digest: HMAC-SHA1
even when the configuration contains cipher none

**Comment by keeshux** [comment]
I would deem this a "wontfix", but I'm certainly open to anyone submitting a PR for that.
