### ISSUE TITLE
Connection issue with macOS 13, Ventura.

### ISSUE THREAD

**Issue by ganaraj-savant** [passepartoutvpn/tunnelkit#304]
Hi,

OpenVPN macOS target was working fine until I updated my macOS to 13. Not able to establish a connection now. Tried to debug using **fetchLastDisconnectError** function provided by Apple starting from macOS 13, getting below error:

Error Domain=TunnelKitOpenVPNManager.OpenVPNProviderConfigurationError Code=1 "(null)"

Everything seems to be fine with my code and configuration, please help.

**Comment by keeshux** [comment]
No issues here with Ventura, nor in general from other users. This report is way too generic.
