### ISSUE TITLE
 mac-catalyst-x86_64 compile error 

### ISSUE THREAD

**Issue by IceSilkworm** [passepartoutvpn/tunnelkit#305]
Problem during make - Please check /Users/ring/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1l.11-fb93d/bin/Catalyst13.0-x86_64.sdk/build-openssl-1.1.1l.log

clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [crypto/aes/aes_cfb.o] Error 1
clang: make[1]: *** [apps/s_cb.o] Error 1
error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [crypto/aes/aes_core.o] Error 1
make[1]: *** [apps/s_socket.o] Error 1
make[1]: *** [apps/bf_prefix.o] Error 1
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [apps/apps.o] Error 1
make[1]: *** [crypto/aes/aes_ecb.o] Error 1
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [crypto/aes/aes_cbc.o] Error 1
make[1]: *** [apps/opt.o] Error 1
make: *** [all] Error 2

**Comment by IceSilkworm** [comment]
This is the log information. Please ask for help. Thanks

**Comment by keeshux** [comment]
Frankly, I can't reproduce this. What machine are you building on?

**Comment by IceSilkworm** [comment]
> Frankly, I can't reproduce this. What machine are you building on?

Mac M1 Max

**Comment by keeshux** [comment]
I also use an M1 for development. No issues. What are you doing?

**Comment by qq5050595531** [comment]
I alos have this probleam. How can I fixed it. found it happen on pod install OpenSSL-Apple/1.1.1l.11
