### ISSUE TITLE
Route all traffic over the tunnel, or not?

### ISSUE THREAD

**Issue by Jdgmx** [passepartoutvpn/tunnelkit#306]
This is a question more than an issue.
I have a case when I need to programmatically switch between sending all network traffic through the VPN, and only send some traffic (allowing internet access).
Similar to what the `NEVPNProtocol.includeAllNetworks` property does.

I looked for `includeAllNetworks` inside the tunnelkit code but it's used as a kill switch. I don't understand what a kill switch has to do with sending all network traffic over the tunnel.

My question is, what is the best way to implement this functionality? Do I have to manually override the routes before or after connecting the vpn, or is there a better way?

Thank you.

**Comment by Jdgmx** [comment]
Anyone?

**Comment by keeshux** [comment]
Have you tried disabling the current use of `.includeAllNetworks` to instead use the flag the way you want?
