### ISSUE TITLE
Multiple VPN configurations

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [passepartoutvpn/tunnelkit#307]
# Summary
Hi, I'm having a multiple VPN configuration problem. In my app, I am trying to support two VPN protocols IPSec and OpenVPN. This is leading to a problem where one of the options can't work if the other configuration option exists. Do you know anything about this behaviour?

**Comment by keeshux** [comment]
IPSec/IKEv2 VPN profiles in iOS coexist with non-native profiles, even if they should really not. Make sure to only keep either native or non-native enabled at a time. Anyway, closing this as out of scope.

**Comment by Bogdan-Belogurov** [comment]
@keeshux Are you planning to expand the lib for IPSec/IKEv2 VPN profiles?

**Comment by keeshux** [comment]
> @keeshux Are you planning to expand the lib for IPSec/IKEv2 VPN profiles?

Maybe, but very low priority. ATM everything is way behind schedule, unfortunately.
