### ISSUE TITLE
Run with xcode14.2 on M1

### ISSUE THREAD

**Issue by yuanshuainiuniu** [passepartoutvpn/tunnelkit#308]
[ -n "" ]
make: *** [/Users/marshal/Library/Developer/Xcode/DerivedData/TunnelKit-bykdvgrneivhknfxbkxezoxrhyks/Build/Intermediates.noindex/TunnelKit.build/Debug-iphonesimulator/wireguard-go-bridge/goroot/.prepared] Error 1
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by yuanshuainiuniu** [comment]
change the path for go in the build_wireguard_go_bridge.sh helped 

like this :
# To ensure we have Go in our path, we add where
# Homebrew generally installs executables
#export PATH=${PATH}:/usr/local/bin:/opt/homebrew/bin
export PATH=${PATH}:/usr/local/go/bin

cd "$wireguard_go_dir" && /usr/bin/make

**Comment by keeshux** [comment]
This is about WireGuard.
