### ISSUE TITLE
After integrating the OpenVpn related modules, the connection has been waiting

### ISSUE THREAD

**Issue by ComedyG** [passepartoutvpn/tunnelkit#320]
# Summary
I integrated the OpenVpn related source code into the project and removed the wireguard related code, but it was still "connecting" when connecting. All the configurations were fine in the previous integrated project, and I don't know why the integration was like this after extracting the specific code.

Hope to give some possible reasons for reference.

![image](https://user-images.githubusercontent.com/18066556/234266499-2c559369-4513-48f6-a8ba-c3300765514d.png)

**Comment by keeshux** [comment]
No details provided, but this is definitely not an issue with the library.
