### ISSUE TITLE
Inherits from "OpenVPNTunnelProvider" and fails to connect

### ISSUE THREAD

**Issue by ComedyG** [passepartoutvpn/tunnelkit#321]
# Summary
I integrated OpenVpn related source code from Tunnelkit into my static library and then connected it to the APP project, but after inherits "PacketTunnelProvider" from "OpenVPNTunnelProvider" in NetworkExtension, The tunnel could not be connected.
### Steps to reproduce
In PacketTunnelProvider File:

class PacketTunnelProvider: OpenVPNTunnelProvider {
    override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        
        dataCountInterval = 3
        super.startTunnel(options: options, completionHandler: completionHandler)
    }
}

Until then, I can guarantee that the VPN configuration and access steps are correct.

### What is the current bug behavior?

State after clicking to connect：
VPNStatusDidChange: disconnected
VPNStatusDidChange: connecting

### What is the expected correct behavior?
VPNStatusDidChange: disconnected
VPNStatusDidChange: connecting
VPNStatusDidChange: connected

I hope you can give me some tips, thanks

**Comment by sergey-zhuravel** [comment]
[ComedyG](https://github.com/ComedyG) did you manage to solve the problem?
