### ISSUE TITLE
How to use private key directly instead of 2048 bit OpenVPN static key

### ISSUE THREAD

**Issue by manglikankit** [passepartoutvpn/tunnelkit#329]
How to use private key directly instead of 2048 bit OpenVPN static key passing in tlsKey variable. I can't convert private key into 20248 bit OPenVPN static key.
Also is there a way to directly .ovpn file data? I need help on this please.

Thanks

**Comment by keeshux** [comment]
Static key encryption is not (and will not be) supported.

**Comment by manglikankit** [comment]
Hi keeshux, Thanks for replying. but I can see in the source code there is passing the ca and 2048 bit static key(Dummy) where as I don't have such key...Well is there any way to connect with OpenVPN by using .ovpn file? If it is please help me how to use.

**Comment by keeshux** [comment]
There's a Demo project for what you need.
