### ISSUE TITLE
Connect via ovpn configuration data

### ISSUE THREAD

**Issue by manglikankit** [passepartoutvpn/tunnelkit#331]
There's a Demo project for what you need.

_Originally posted by @keeshux in https://github.com/passepartoutvpn/tunnelkit/issues/329#issuecomment-1668578664_
            
Hi, Davide,
I'm configured the all inputs as following:
 do {
            let parser = try? OpenVPN.ConfigurationParser.parsed(fromContents: ovpnConfigSTR)
            
            textServer.text = parser?.configuration.dnsTLSServerName
            textDomain.text = parser?.configuration.dnsDomain
            textPort.text = "443"
            switchTCP.isOn = false
            textUsername.text = username
            textPassword.text = password
        }

and make method :

static func make(params: Parameters) -> OpenVPN.ProviderConfiguration {
            var builder = OpenVPN.ConfigurationBuilder()
            builder.ca = ca
            builder.cipher = .aes256cbc
            builder.digest = .sha1
            builder.compressionFraming = .compLZO
            builder.renegotiatesAfter = nil
            builder.remotes = [Endpoint(params.hostname, EndpointProtocol(params.socketType, params.port))]
            builder.tlsWrap = TLSWrap(strategy: .auth, key: tlsKey)
            builder.mtu = 1350
            builder.routingPolicies = [.IPv4, .IPv6]
            let cfg = builder.build()

            var providerConfiguration = OpenVPN.ProviderConfiguration(params.title, appGroup: params.appGroup, configuration: cfg)
            providerConfiguration.shouldDebug = true
            providerConfiguration.masksPrivateData = false
            return providerConfiguration
        }

Also changed the vc value of variable : static let ca = OpenVPN.CryptoContainer(pem: """,
but for static let tlsKey = OpenVPN.StaticKey(file: """.  It is same as it is 'coz can't convert into 2048 bit statickey.
I've configures all the app group and bundleidentifier also.

Still I am unable to connect.
 Do you have any video link where you are connecting with .ovpn file? It would help me much more. I need to connect only in iPhone/iPad devices. Please find the attached sample doc file through which I need to connect.
[ovpn-config.docx](https://github.com/passepartoutvpn/tunnelkit/files/12288263/ovpn-config.docx)

**Comment by keeshux** [comment]
Dude, this is not an issue.

**Comment by manglikankit** [comment]
Hey Davide,
I know this is not an issue but just asking for your help please.
