### ISSUE TITLE
Tunnel connection is not creating successfully

### ISSUE THREAD

**Issue by manglikankit** [passepartoutvpn/tunnelkit#332]
# Summary
**Its not an issue in Demo code but something went wrong with my code**
After configure all the thing I am getting below logs:

VPNStatusDidChange: disconnected
12:49:37 DEBUG NetworkExtensionVPN.notifyStatus():242 - VPN status did change (com.prosoft.mLite.Tunnel): isEnabled=true, status=1
12:49:37 DEBUG NetworkExtensionVPN.notifyReinstall():228 - VPN did reinstall (com.prosoft.mLite.Tunnel): isEnabled=true
12:49:37 DEBUG NetworkExtensionVPN.notifyReinstall():228 - VPN did reinstall (com.prosoft.mLite.Tunnel): isEnabled=true
VPNStatusDidChange: connecting
12:49:37 DEBUG NetworkExtensionVPN.notifyStatus():242 - VPN status did change (com.prosoft.mLite.Tunnel): isEnabled=true, status=2
VPNStatusDidChange: disconnecting
12:49:37 DEBUG NetworkExtensionVPN.notifyStatus():242 - VPN status did change (com.prosoft.mLite.Tunnel): isEnabled=true, status=5
VPNStatusDidChange: disconnected
12:49:37 DEBUG NetworkExtensionVPN.notifyStatus():242 - VPN status did change (com.prosoft.mLite.Tunnel): isEnabled=true, status=1

Can someone help me on this pls?

### Steps to reproduce
Click the Connect button only.

### What is the current bug behavior?
VPNStatusDidChange: disconnected

### What is the expected correct behavior?
VPNStatusDidChange: Connected

**Comment by keeshux** [comment]
Please, this is the very last warning.

**Comment by sergey-zhuravel** [comment]
[manglikankit](https://github.com/manglikankit) did you manage to solve the problem?
