### ISSUE TITLE
Apple tvOS Support

### ISSUE THREAD

**Issue by NextstackLLC** [passepartoutvpn/tunnelkit#337]
Hello 

I'm currently using the TunnelKit pod in one of my projects and noticed that there isn't support for Apple tvOS. Considering the growing popularity of Apple TV apps, it would be beneficial to have tvOS support in TunnelKit.

I tried integrating TunnelKit with a tvOS project and faced issues, which prompted me to open this request.
I understand that adding tvOS support might involve some architectural changes or tweaks, but it would be greatly appreciated by the community. Please let me know if you need more information or if there are any plans already in place to support tvOS in the future.

Thank you for your consideration!

---

_EDIT_

- [x] Add tvOS targets to OpenSSL binaries
- [x] Look into adding tvOS platform in WireGuardKit
- [x] Add platform to Package.swift
- [x] Update Demo project

**Comment by keeshux** [comment]
Last week I bought an Apple TV. :-)

**Comment by NextstackLLC** [comment]
@keeshux sound good :-)

**Comment by scottzest** [comment]
@keeshux any update on tvOS support being added?

**Comment by keeshux** [comment]
Not yet @scottzest

**Comment by keeshux** [comment]
@NextstackLLC out of curiosity, are you aware of the GPL?

**Comment by zEstLabs** [comment]
> @NextstackLLC out of curiosity, are you aware of the GPL?

Can you enlighten me here please? @keeshux

**Comment by keeshux** [comment]
> > @NextstackLLC out of curiosity, are you aware of the GPL?
> 
> Could you enlighten me here please? @keeshux

> I'm currently using the TunnelKit pod in one of my projects

If your creation is in the public domain, whatever the form, your software must comply with the GPL too.

**Comment by NextstackLLC** [comment]
@keeshux hi, can you elaborate regarding GPL? Just FYI, In general I know, this is general public license

**Comment by keeshux** [comment]
So I assume this project of yours is a private one.

**Comment by scottzest** [comment]
> > > @NextstackLLC out of curiosity, are you aware of the GPL?
> 
> > 
> 
> > Could you enlighten me here please? @keeshux
> 
> 
> 
> > I'm currently using the TunnelKit pod in one of my projects
> 
> 
> 
> If your creation is in the public domain, whatever the form, your software must comply with the GPL too.

Ah this is fine out project is open source, I just wondered if there was anything I missed, thanks for the clarification.

I see quite a bit of activity lately, without meaning to add any pressure would this activity be leading us towards compatibility of TvOS?

**Comment by keeshux** [comment]
<img width="1411" alt="Screenshot 2023-12-16 at 16 18 36" src="https://github.com/passepartoutvpn/tunnelkit/assets/805724/6376650f-593a-49af-8703-af86242b60cd">

**Comment by keeshux** [comment]
> Ah this is fine our project is open source, I just wondered if there was anything I missed, thanks for the clarification.

Would you mind sharing it? Your GitHub is pretty bare.

**Comment by scottzest** [comment]
> > Ah this is fine our project is open source, I just wondered if there was anything I missed, thanks for the clarification.
> 
> Would you mind sharing it? Your GitHub is pretty bare.

This is a fair few commits behind current development version, I recently inherited maintenance of this app and tvOS is a priority now https://github.com/vpnuk/apps

**Comment by keeshux** [comment]
Okay, this is pretty much done. I will push the update around January though.

**Comment by scottzest** [comment]
> Okay, this is pretty much done. I will push the update around January though.

Great work! Looking forward to it!
