### ISSUE TITLE
XOR Patch Feature

### ISSUE THREAD

**Issue by XMB5** [passepartoutvpn/tunnelkit#38]
# Summary
One useful feature that can be added to OpenVPN is the [scramble xor patch](https://tunnelblick.net/cOpenvpn_xorpatch.html) (<a href="https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.6/patches">github</a>). It XORs all bytes sent by openvpn, evading firewalls. It would be a great addition to passepartout that would make it stand out from the official iOS OpenVPN app, and it should be relatively simple to implement.

[Original reddit post](https://www.reddit.com/r/passepartout/comments/9pnxsv/openvpn_xor_patch/)

**Comment by stevemurray1990** [comment]
Has this been added? If so, it would be great if you can share a demo implementation for iOS and MacOS. :)

**Comment by keeshux** [comment]
Open issue = not (yet?) 😎

**Comment by tmthecoder** [comment]
I'd be open to helping with this, but do not have much of knowhow on adding this vs implementing it in OpenVPN itself. On OpenVPN you can just patch it, would you mind giving me a rundown on what is similar code-related on here and OpenVPN?

**Comment by keeshux** [comment]
@tmthecoder there's a PR open.

**Comment by tmthecoder** [comment]
@keeshux my bad if there's anything I can do to help, I'm available as I am looking for an active xor capable client as well

**Comment by joosthoogendoorn** [comment]
Isn't tls-crypt, which is already supported, more effective or the same in effectiveness in bypassing firewalls? I have customers happily using OpenVPN with tls-crypt enabled to bypass the GFW, without xorpatch.

**Comment by tmthecoder** [comment]
@joosthoogendoorn Based in my experimentation with tls-crypt vs xor patch I've found the xor patch to obfuscate the packet more with tls-crypt being detectable as an openvpn packet if listening for them. Xor on the other hand ends up making it unknown traffic, at least according to my own private testing. Personally, I use both in combination as xor can be decrypted at times but tls-crypt also adds that extra tls layer of encryption

**Comment by bra1nslayer** [comment]
@keeshux I think proxy.sh safejumper already implemented xor feature.I am not an expert on ios code but please have a check if helps **https://github.com/proxysh/Safejumper-for-iOS**
@tmthecoder yes i tottaly agree with you. tls-crypt is an option for evading DPI firewalls but not as effective as xor in my case also detected by firewall time to time.(i have been using xor on android for almost 2 years no issues at all.) I think it depends on DPI software which changes by goverment or ISP.

**Comment by bra1nslayer** [comment]
Any news on subject?

**Comment by HosseyNJF** [comment]
+1

**Comment by makoni** [comment]
@keeshux do you have any plans for that one? I see that there's PR already for that: https://github.com/passepartoutvpn/tunnelkit/pull/170

Would love to see that feature in TunnelKit 🤞
