### ISSUE TITLE
Trouble Connecting to OpenVPN Server Using Tunnelkit Library

### ISSUE THREAD

**Issue by koust** [passepartoutvpn/tunnelkit#401]
I'm using the Tunnelkit library in my project. I cannot connect to the OpenVPN server I created, but I can successfully connect using the OpenVPN application. I have logged the details, but couldn't find any specifics.

Has anyone experienced this before?

I'm waiting for your help, thank you.

**Comment by keeshux** [comment]
This is not a library issue, it's a support request. Closing.
