### ISSUE TITLE
Unable to connect WireGuard on TV OS

### ISSUE THREAD

**Issue by 7mada123** [passepartoutvpn/tunnelkit#402]
When trying to connect on apple tv, the status immediately change from connecting to disconnected

The error message I got from `fetchLastDisconnectError` method

```
Error Domain=NEVPNConnectionErrorDomain Code=12 "The VPN session failed because an internal error occurred." UserInfo={NSLocalizedDescription=The VPN session failed because an internal error occurred.}
```

The WireGuard configuration has been added without any issue and I have double check my integration but I couldn't figure out what is wrong

**Comment by keeshux** [comment]
Please refer to the Demo project and read the README carefully (e.g. entitlements). This has been asked (and answered) multiple times.
