### ISSUE TITLE
Error: Demo App not working

### ISSUE THREAD

**Issue by Aploide** [passepartoutvpn/tunnelkit#410]
# Summary
Demo not working

### Steps to reproduce
Open the demo, change/or keep the configuration variables, put the credentials and try to connect

### What is the current bug behavior?
the vpn profile loads in the iPhone settings, but it doesn't connect

### What is the expected correct behavior?
when clicking "connect" it should say "connecting" then "connected"

### Relevant logs and/or screenshots

this is what it says

```swift
VPNStatusDidChange: disconnected
VPNStatusDidChange: disconnected
VPNStatusDidChange: connecting
VPNStatusDidChange: disconnected
```

**Comment by keeshux** [comment]
Duplicate, check out the README.

**Comment by NirmitDagly** [comment]
Hi @Aploide  I am trying to run the demo and facing the same issue as yours. I have verified the CA and TLS keys being used are correct and played with the configuration settings but still no luck.

Has this issue been resolved for you?

**Comment by Aploide** [comment]
@NirmitDagly It didn't, I had to skip using this library
