### ISSUE TITLE
App Store Rejection: Privacy manifest files

### ISSUE THREAD

**Issue by NasrullahKhan** [passepartoutvpn/tunnelkit#423]
ITMS-91065: Missing signature - Your app includes “Frameworks/openssl.framework/openssl”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

Apple Developer Relations

**Comment by keeshux** [comment]
Are you serious?
