### ISSUE TITLE
Implement floating

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/tunnelkit#75]
Attempted implementation was broken and was therefore [reverted](https://github.com/passepartoutvpn/tunnelkit/commit/9c0205614b80ed14cb5435f8f03ecdcdf10e54d1).

This was apparent on network change with providers supporting floating:

- TunnelBear
- NordVPN
- Mullvad
- ...many others

The VPN remained active but no data flowed. It must take more than rebinding the socket, something is just off. At times servers (like Mullvad) send new CONTROL_V1 packets on rebind to reinitiate some TLS handshake.

**Comment by keeshux** [comment]
Might want to shut down on network change until this is sorted out.

**Comment by jeroenleenarts** [comment]
Hi @keeshux , perhaps this might help with solving this issue?
WireGuard has dealt with the same issue you seem to be describing in this issue.
https://git.zx2c4.com/wireguard-ios/commit/?id=99f0e457c34480f25582d7b4ed509404712c648c

**Comment by keeshux** [comment]
> Hi @keeshux , perhaps this might help with solving this issue?
> WireGuard has dealt with the same issue you seem to be describing in this issue.
> https://git.zx2c4.com/wireguard-ios/commit/?id=99f0e457c34480f25582d7b4ed509404712c648c

Thanks for the hint but the solution is tightly bound to the software. OpenVPN in this case. It seems that for some providers rebinding the socket is not sufficient, but I haven't investigated further for now.
