### ISSUE TITLE
Possible issue in Demo App

### ISSUE THREAD

**Issue by abwizeline** [passepartoutvpn/tunnelkit#99]
# Summary

Hi keeshux, i am getting issue and not sure it's related to tunnelkit or not. After launching Demo App and trying to fill everything (manually). When i want to start VPN i am getting Update Required in VPN Profiles (for IOS 12)

### Steps to reproduce
Try to add any OpenVPN details in IOS 12

### What is the expected correct behavior?
Should be starting without problems

**Comment by keeshux** [comment]
https://forums.openvpn.net/viewtopic.php?t=27123
